force-app/main/default/objects/Case/fields/FEC_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>FEC_Account_Number__c</fullName>
    <label>Account Number</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/FEC_Account_or_Contract__c.field-meta.xml
<CustomField>
    <fullName>FEC_Account_or_Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account/ Contract Number</label>
    <referenceTo>FEC_Customer_History__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/FEC_Case_ID__c.field-meta.xml
<CustomField>
    <fullName>FEC_Case_ID__c</fullName>
    <formula>IF(
    OR(
        RecordType.Name = 'Customer Case',
        RecordType.Name = 'Internal Case',
        RecordType.Name = 'SFT Case'
    ),
    HYPERLINK("/" &amp; Id, FEC_ID_Search__c, "_self"),
    ''
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Case ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/FEC_Case_Status__c.field-meta.xml
<CustomField>
    <fullName>FEC_Case_Status__c</fullName>
    <description>Trạng thái cuối hiển thị trên Case bao gồm  thông  tin đơn vị đang pending case với các case pending</description>
    <label>Case Status</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/FEC_Channel__c.field-meta.xml
<CustomField>
    <fullName>FEC_Channel__c</fullName>
    <label>Channel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Channel</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/FEC_Created_by__c.field-meta.xml
<CustomField>
    <fullName>FEC_Created_by__c</fullName>
    <description>Hiển thị Email ID của người tạo Interaction
Trường tạo mới để đáp ứng hiển thị trên giao diện và listview</description>
    <formula>IF(
OR(
TRIM(LOWER(CreatedBy.LastName)) = &quot;platform integration user&quot;,
TRIM(LOWER(CreatedBy.Alias)) = &quot;platint&quot;
),
&quot;system&quot;,
IF(
RecordType.Name = &quot;Interaction&quot;,
LEFT(CreatedBy.Email, FIND(&quot;@&quot;, CreatedBy.Email) - 1),
&quot;&quot;
)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Interaction Created By</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/FEC_Created_On__c.field-meta.xml
<CustomField>
    <fullName>FEC_Created_On__c</fullName>
    <formula>CreatedDate</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Created On</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case/fields/FEC_External_Interaction_ID__c.field-meta.xml
<CustomField>
    <fullName>FEC_External_Interaction_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>External Interaction ID</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Case/fields/FEC_Interaction__c.field-meta.xml
<CustomField>
    <fullName>FEC_Interaction__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Trường lookup hiển thị Interaction sinh ra Case</description>
    <label>Interaction ID</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Cases (Interaction)</relationshipLabel>
    <relationshipName>Cases1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/FEC_Interaction_Email__c.field-meta.xml
<CustomField>
    <fullName>FEC_Interaction_Email__c</fullName>
    <label>Interaction Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Case/fields/FEC_Interaction_End_On__c.field-meta.xml
<CustomField>
    <fullName>FEC_Interaction_End_On__c</fullName>
    <description>Thời điểm tương tác kết thúc</description>
    <label>Interaction End On</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case/fields/FEC_Interaction_ID__c.field-meta.xml
<CustomField>
    <fullName>FEC_Interaction_ID__c</fullName>
    <description>Trường thông tin trạng thái Case lấy theo ID để phục vụ hiển thị ở giao diện Case theo yêu cầu FEC</description>
    <formula>IF(
  RecordType.Name = &apos;Interaction&apos;,
  HYPERLINK(&quot;/&quot; &amp; Id, FEC_ID_Search__c, &quot;_self&quot;),
  IF(
    FEC_Interaction__c &lt;&gt; null,
    HYPERLINK(&quot;/&quot; &amp; FEC_Interaction__r.Id, FEC_Interaction__r.FEC_ID_Search__c, &quot;_self&quot;),
    IF(
      NOT(ISBLANK(ArchiveInteractionId__c)),
      HYPERLINK(&quot;/apex/ArchiveInteractionCaseRedirect?id=&quot; &amp; Id, ArchiveInteractionId__c, &quot;_self&quot;),
      &apos;&apos;
    )
  )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Interaction ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/FEC_Interaction_Masked_Phone__c.field-meta.xml
<CustomField>
    <fullName>FEC_Interaction_Masked_Phone__c</fullName>
    <formula>IF(
    ISBLANK( FEC_Phone_Number__c ),
    &quot;&quot;,
    LEFT(FEC_Phone_Number__c , 4)
    &amp; &quot;***&quot;
    &amp; RIGHT(FEC_Phone_Number__c , 3)
)</formula>
    <label>Interaction Phone</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/FEC_Interaction_Status__c.field-meta.xml
<CustomField>
    <fullName>FEC_Interaction_Status__c</fullName>
    <description>Trường thông tin trạng thái Case lấy theo Final status để phục vụ hiển thị ở giao diện Case theo yêu cầu FEC</description>
    <formula>IF( RecordType.Name = &apos;Interaction&apos; ,  FEC_Final_Status__c  , &apos;&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Interaction Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/FEC_Interaction_Subchannel__c.field-meta.xml
<CustomField>
    <fullName>FEC_Interaction_Subchannel__c</fullName>
    <description>Kênh tương tác phụ</description>
    <label>Interaction Sub Channel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Inbound Call</fullName>
            </value>
            <value>
                <fullName>Outbound Call</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/FEC_Last_Updated_By__c.field-meta.xml
<CustomField>
    <fullName>FEC_Last_Updated_By__c</fullName>
    <description>Email ID của người chỉnh sửa gần nhất
Trường tạo mới để hiển thị trên Case details và interaction details do trường standard không hiển thị được đúng  yêu cầu</description>
    <formula>IF(
    OR(
        TRIM(LOWER( LastModifiedBy.LastName)) = &quot;platform integration user&quot;,
        TRIM(LOWER(LastModifiedBy.Alias)) = &quot;platint&quot;
    ),
    &quot;system&quot;,
    IF(
        RecordType.Name = &quot;Interaction&quot;,
        LEFT(LastModifiedBy.Email,FIND(&quot;@&quot;,LastModifiedBy.Email)-1),
        &quot;&quot;
    )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Last Updated By</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/FEC_Last_Updated_On__c.field-meta.xml
<CustomField>
    <fullName>FEC_Last_Updated_On__c</fullName>
    <description>Trường tạo mới để hiển thị trên Case details và interaction details do trường standard không hiển thị được đúng  yêu cầu</description>
    <formula>LastModifiedDate</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Last Updated On</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case/fields/FEC_Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>FEC_Phone_Number__c</fullName>
    <description>Số điện thoại khách hàng đã liên hệ</description>
    <label>Interaction Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Case/fields/FEC_SubCategory__c.field-meta.xml
<CustomField>
    <fullName>FEC_SubCategory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Thông tin danh mục phụ</description>
    <label>Sub Category</label>
    <referenceTo>FEC_Sub_Category__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/FEC_SubCode__c.field-meta.xml
<CustomField>
    <fullName>FEC_SubCode__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Thông tin danh mục con</description>
    <label>Updated Sub Code</label>
    <referenceTo>FEC_Sub_Code__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Interaction.recordType-meta.xml
<RecordType>
    <fullName>Interaction</fullName>
    <active>true</active>
    <businessProcess>Interaction Process</businessProcess>
    <label>Interaction</label>
</RecordType>

force-app/main/default/objects/FEC_Customer_History__c/FEC_Customer_History__c.object-meta.xml
<CustomObject>
    <label>Customer History</label>
    <nameField>
        <label>Customer History Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Histories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FEC_Customer_History__c/fields/FEC_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>FEC_Account_Number__c</fullName>
    <description>Số tài khoản</description>
    <inlineHelpText>Số TK khách hàng</inlineHelpText>
    <label>Account Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FEC_Sensitive_Data__c/FEC_Sensitive_Data__c.object-meta.xml
<CustomObject>
    <description>Lịch sử từng lần xem dữ liệu nhạy cảm của các User trên CSM (Click vào biểu tượng eye icon)</description>
    <label>Sensitive Data</label>
    <nameField>
        <label>Sensitive Data Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sensitive Data</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FEC_Sensitive_Data__c/fields/FEC_Case_ID__c.field-meta.xml
<CustomField>
    <fullName>FEC_Case_ID__c</fullName>
    <description>Case ID sẽ hiển thị dạng. hyperlink, khi click vào sẽ hiển thị Case Review</description>
    <formula>FEC_Related_Case__r.FEC_Link_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Case ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FEC_Sensitive_Data__c/fields/FEC_Related_Case__c.field-meta.xml
<CustomField>
    <fullName>FEC_Related_Case__c</fullName>
    <description>Hiển lookup đến Case/Interaction liên quan</description>
    <label>Related Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Sensitive Data</relationshipLabel>
    <relationshipName>Sensitive_Data</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FEC_Sensitive_Data__c/fields/FEC_Section__c.field-meta.xml
<CustomField>
    <fullName>FEC_Section__c</fullName>
    <description>Hiển thị tên section mà tại đó User chọn xem đầy đủ sensitive data (click eye icon)</description>
    <label>Section</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FEC_Sensitive_Data__c/fields/FEC_User__c.field-meta.xml
<CustomField>
    <fullName>FEC_User__c</fullName>
    <description>Hệ thống ghi nhận &lt;Email ID&gt; của User xem dữ liệu</description>
    <label>User</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FEC_Sensitive_Data__c/fields/FEC_User_Role__c.field-meta.xml
<CustomField>
    <fullName>FEC_User_Role__c</fullName>
    <description>Role của User xem data tại thời điểm xem
(không dùng đc formula vì khi User đổi role thì không đc cập nhật mà chỉ ghi nhận tại thời điểm xem dữ liệu)</description>
    <label>User Role</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FEC_Sub_Category__c/FEC_Sub_Category__c.object-meta.xml
<CustomObject>
    <label>FEC Sub Category</label>
    <nameField>
        <label>Sub Category  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FEC Sub Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FEC_Sub_Category__c/fields/FEC_Code__c.field-meta.xml
<CustomField>
    <fullName>FEC_Code__c</fullName>
    <description>Mã Code danh mục phụ</description>
    <externalId>true</externalId>
    <label>Code</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/FEC_Sub_Category__c/fields/FEC_Name_VN__c.field-meta.xml
<CustomField>
    <fullName>FEC_Name_VN__c</fullName>
    <description>Tên tiếng Việt của danh mục phụ</description>
    <label>Name VN</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FEC_Sub_Code__c/FEC_Sub_Code__c.object-meta.xml
<CustomObject>
    <label>FEC_Sub Code</label>
    <nameField>
        <label>FEC_Sub Code Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FEC_Sub Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FEC_Sub_Code__c/fields/FEC_Code__c.field-meta.xml
<CustomField>
    <fullName>FEC_Code__c</fullName>
    <description>Mã Code danh mục con</description>
    <label>Code</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/FEC_Sub_Code__c/fields/FEC_Name_VN__c.field-meta.xml
<CustomField>
    <fullName>FEC_Name_VN__c</fullName>
    <description>Tên tiếng Việt của danh mục con</description>
    <label>Name VN</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Channel.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Inbound</fullName>
    </customValue>
    <customValue>
        <fullName>Outbound</fullName>
    </customValue>
    <customValue>
        <fullName>Chat</fullName>
    </customValue>
    <customValue>
        <fullName>Email</fullName>
    </customValue>
    <customValue>
        <fullName>F2F</fullName>
    </customValue>
    <customValue>
        <fullName>Letter</fullName>
    </customValue>
    <customValue>
        <fullName>External</fullName>
    </customValue>
    <customValue>
        <fullName>Internal</fullName>
    </customValue>
    <customValue>
        <fullName>Social &amp; Media</fullName>
    </customValue>
    <customValue>
        <fullName>Research</fullName>
    </customValue>
    <masterLabel>Channel</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/FEC_InteractionInforHandler.cls
public without sharing class FEC_InteractionInforHandler {
    @AuraEnabled(cacheable=true)
    public static Case getInteraction(Id recordId) {
        List<Case> caseList = [
        SELECT FEC_Interaction_Masked_Phone__c,
               FEC_Channel__c,
               FEC_Interaction_Subchannel__c,
               FEC_Created_On__c,
               FEC_Created_by__c,
               FEC_External_Interaction_ID__c,
               FEC_Last_Updated_On__c,
               FEC_Last_Updated_By__c
        FROM Case
        WHERE Id = :recordId
    ];
        
        return caseList.isEmpty() ? null : caseList[0];
    }
    
    @AuraEnabled
    public static String getInteractionPhoneReveal(Id recordId) {
        
        Case c = [
        SELECT Id, FEC_Phone_Number__c, FEC_Interaction_ID__c
        FROM Case
        WHERE Id = :recordId
        LIMIT 1
    ];
        
        User u = [
        SELECT Username, UserRole.Name
        FROM User
        WHERE Id = :UserInfo.getUserId()
    ];
        
        
        // 🔐 Audit sensitive access
        FEC_CommonUltils.logSensitiveAccess(
            'Interaction Details',
        'Interaction Phone',
        u.Username.split('@')[0],
        u.UserRole != null ? u.UserRole.Name : null,
        c.Id
            );
        
        // FEC_Sensitive_Data__c sensitiveData = new FEC_Sensitive_Data__c(
        //     FEC_Section__c = 'Interaction Details',
        // Name = 'Interaction Phone',
        // FEC_User__c = u.Username.split('@')[0],
        // FEC_User_Role__c = u.UserRole != null ? u.UserRole.Name : null,
        // FEC_Related_Case__c = c.Id
        //     );
        // insert sensitiveData;
        
        return c.FEC_Phone_Number__c;
    }
    
    
    @AuraEnabled
    public static String  updateInteractionPhone(Id recordId, String phone) {
        Case c = new Case(
            Id = recordId,
        FEC_Phone_Number__c = phone
            );
        update c;
        
        // return masked phone
        return maskPhone(phone);
    }
    
    
    private static String maskPhone(String phone) {
        if (String.isBlank(phone)) {
            return phone;
        }
        
        Integer len = phone.length();
        
        // Nếu quá ngắn thì không mask
        if (len <= 7) {
            return phone;
        }
        
        return phone.substring(0, 4)
            + '***'
            + phone.substring(len - 3);
    }
    
    @AuraEnabled(cacheable=true)
    public static Case getInteractionHighlightData(Id recordId) {
        List<Case> caseList = [
        SELECT FEC_Interaction_ID__c,
               FEC_Interaction_Status__c,
               FEC_Last_Updated_On__c,
               FEC_Last_Updated_By__c
               
        FROM Case
        WHERE Id = :recordId
    ];
        
        return caseList.isEmpty() ? null : caseList[0];
    }
    
    @AuraEnabled(cacheable=true)
    public static List<Case> getRelevantInteractions(Id recordId) {
        
        // Lấy Interaction hiện tại
        Case currentInteraction = getCurrentInteraction(recordId);
        System.debug('Current Interaction: ' + currentInteraction);
        if (currentInteraction == null) {
            return new List<Case>();
        }
        
        // TÁCH BIẾN – BẮT BUỘC
        String phone = currentInteraction.FEC_Phone_Number__c;
        String email = currentInteraction.FEC_Interaction_Email__c;
        DateTime closeDt = currentInteraction.ClosedDate;
        // Nếu không có Phone & Email → không search
        if (String.isBlank(phone) && String.isBlank(email)) {
            return new List<Case>();
        }
        
        // Build điều kiện match Phone / Email
        List<String> matchConditions = new List<String>();
        
        if (String.isNotBlank(phone)) {
            matchConditions.add('FEC_Phone_Number__c = :phone');
        }
        if (String.isNotBlank(email)) {
            matchConditions.add('FEC_Interaction_Email__c = :email');
        }
        
        DateTime archiveThreshold;
        if (closeDt != null) {
            archiveThreshold = DateTime.now().addMonths(-3);
        }
        
        // =====================================================
        // 5. BUILD WHERE CONDITIONS (DYNAMIC)
        // =====================================================
        List<String> whereConditions = new List<String>();
        whereConditions.add('RecordType.DeveloperName = \'Interaction\'');
        whereConditions.add('Id != :recordId');
        whereConditions.add('(' + String.join(matchConditions, ' OR ') + ')');
        
        if (archiveThreshold != null) {
            whereConditions.add('FEC_Interaction_End_On__c  >= :archiveThreshold');
        }
        
        
        // SOQL cuối cùng
        String soql =
            'SELECT Id, ' +
            '       FEC_Interaction_ID__c, ' +
            '       FEC_Channel__c, ' +
            '       FEC_Created_On__c ' +
            'FROM Case ' +
            'WHERE ' + String.join(whereConditions, ' AND ') + ' ' +
            'ORDER BY FEC_Last_Updated_On__c DESC ' +
            'LIMIT 5';
        System.debug('SOQL: ' + soql);
        return Database.query(soql);
    }
    
    @AuraEnabled(cacheable=true)
    public static List<Case> getRelevantInteractionsViewAll(Id recordId) {
        
        // Lấy Interaction hiện tại
        Case currentInteraction = getCurrentInteraction(recordId);
        System.debug('Current Interaction: ' + currentInteraction);
        if (currentInteraction == null) {
            return new List<Case>();
        }
        
        // TÁCH BIẾN – BẮT BUỘC
        String phone = currentInteraction.FEC_Phone_Number__c;
        String email = currentInteraction.FEC_Interaction_Email__c;
        DateTime closeDt = currentInteraction.ClosedDate;
        // Nếu không có Phone & Email → không search
        if (String.isBlank(phone) && String.isBlank(email)) {
            return new List<Case>();
        }
        
        // Build điều kiện match Phone / Email
        List<String> matchConditions = new List<String>();
        
        if (String.isNotBlank(phone)) {
            matchConditions.add('FEC_Phone_Number__c = :phone');
        }
        if (String.isNotBlank(email)) {
            matchConditions.add('FEC_Interaction_Email__c = :email');
        }
        
        DateTime archiveThreshold;
        if (closeDt != null) {
            archiveThreshold = DateTime.now().addMonths(-3);
        }
        
        // =====================================================
        // 5. BUILD WHERE CONDITIONS (DYNAMIC)
        // =====================================================
        List<String> whereConditions = new List<String>();
        whereConditions.add('RecordType.DeveloperName = \'Interaction\'');
        whereConditions.add('Id != :recordId');
        whereConditions.add('(' + String.join(matchConditions, ' OR ') + ')');
        
        if (archiveThreshold != null) {
            whereConditions.add('ClosedDate >= :archiveThreshold');
        }
        
        // SOQL cuối cùng
        String soql =
            'SELECT Id, ' +
            '       FEC_Interaction_ID__c,FEC_Interaction_Status__c, ' +
            '       FEC_Channel__c, ' +
            '       FEC_Created_On__c,FEC_Created_by__c ' +
            'FROM Case ' +
            'WHERE ' + String.join(whereConditions, ' AND ') + ' ' +
            'ORDER BY FEC_Last_Updated_On__c DESC ';
        System.debug('SOQL: ' + soql);
        return Database.query(soql);
    }
    
    
    @AuraEnabled(cacheable=true)
    public static Integer getRelevantInteractionsViewAllCount(Id recordId) {
        
        // Lấy Interaction hiện tại
        Case currentInteraction = getCurrentInteraction(recordId);
        if (currentInteraction == null) {
            return 0;
        }
        
        // TÁCH BIẾN – BẮT BUỘC
        String phone = currentInteraction.FEC_Phone_Number__c;
        String email = currentInteraction.FEC_Interaction_Email__c;
        DateTime closeDt = currentInteraction.ClosedDate;
        // Nếu không có Phone & Email → không search
        if (String.isBlank(phone) && String.isBlank(email)) {
            return 0;
        }
        
        // Build điều kiện match Phone / Email
        List<String> matchConditions = new List<String>();
        
        if (String.isNotBlank(phone)) {
            matchConditions.add('FEC_Phone_Number__c = :phone');
        }
        if (String.isNotBlank(email)) {
            matchConditions.add('FEC_Interaction_Email__c = :email');
        }
        
        DateTime archiveThreshold;
        if (closeDt != null) {
            archiveThreshold = DateTime.now().addMonths(-3);
        }
        
        // =====================================================
        // 5. BUILD WHERE CONDITIONS (DYNAMIC)
        // =====================================================
        List<String> whereConditions = new List<String>();
        whereConditions.add('RecordType.DeveloperName = \'Interaction\'');
        whereConditions.add('Id != :recordId');
        whereConditions.add('(' + String.join(matchConditions, ' OR ') + ')');
        
        if (archiveThreshold != null) {
            whereConditions.add('ClosedDate >= :archiveThreshold');
        }
        
        
        
        // SOQL COUNT
        String soql =
            'SELECT COUNT() ' +
            'FROM Case ' +
            'WHERE ' + String.join(whereConditions, ' AND ') + ' '; 
            
        System.debug('SOQL COUNT: ' + soql);
        
        return Database.countQuery(soql);
    }
    
    
    @AuraEnabled(cacheable=true)
    public static List<Case> getCaseList(Id recordId) {
        try {
            List<Case> caseList = [SELECT Id,
                                       FEC_Case_ID__c,
                                       FEC_Case_Status__c,
                                       FEC_SubCategory__c,
                                       FEC_SubCategory__r.FEC_Code__c,
                                       FEC_SubCategory__r.FEC_Name_VN__c,
                                       FEC_SubCode__c,
                                       FEC_SubCode__r.FEC_Code__c,
                                       FEC_SubCode__r.FEC_Name_VN__c
                                FROM Case
                                WHERE FEC_Interaction__c = :recordId
                                LIMIT 5];
            return caseList;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
    
    @AuraEnabled(cacheable=true)
    public static Integer getCaseTotal(Id recordId) {
        try {
            Integer totalCases = [
            SELECT COUNT()
            FROM Case
            WHERE FEC_Interaction__c = :recordId
        ];
            return totalCases;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
    
    
    @AuraEnabled(cacheable=true)
    public static List<Case> getCaseListViewAll(Id recordId) {
        try {
            List<Case> caseList = [SELECT Id,
                                       FEC_Case_ID__c,
                                       FEC_Case_Status__c,
                                       FEC_SubCategory__c,
                                       FEC_SubCategory__r.FEC_Code__c,
                                       FEC_SubCategory__r.FEC_Name_VN__c,
                                       FEC_SubCode__c,
                                       FEC_SubCode__r.FEC_Code__c,
                                       FEC_SubCode__r.FEC_Name_VN__c,
                                       FEC_Account_or_Contract__r.FEC_Account_Number__c,
                                       FEC_Case_Created_By__c,
                                       FEC_Case_Created_On__c
                                FROM Case
                                WHERE FEC_Interaction__c = :recordId
                                ORDER BY FEC_Case_Created_On__c DESC
                                ];
            return caseList;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
    
    @AuraEnabled(cacheable=true)
    public static List<Case> getRelevantCases(Id recordId) {
        
        // =====================================================
        // 1. LẤY INTERACTION HIỆN TẠI
        // =====================================================
        Case currentInteraction = getCurrentInteraction(recordId);
        if (currentInteraction == null) {
            return new List<Case>();
        }
        
        // =====================================================
        // 2. TÁCH BIẾN – RÕ NGHĨA
        // =====================================================
        String phone     = currentInteraction.FEC_Phone_Number__c;
        String email     = currentInteraction.FEC_Interaction_Email__c;
        DateTime closeDt = currentInteraction.ClosedDate;
        
        // Không có Phone & Email → không search
        if (String.isBlank(phone) && String.isBlank(email)) {
            return new List<Case>();
        }
        
        // =====================================================
        // 3. BUILD MATCH CONDITIONS (PHONE / EMAIL)
        // =====================================================
        List<String> matchConditions = new List<String>();
        
        if (String.isNotBlank(phone)) {
            matchConditions.add('FEC_Interaction__r.FEC_Phone_Number__c = :phone');
        }
        if (String.isNotBlank(email)) {
            matchConditions.add('FEC_Interaction__r.FEC_Interaction_Email__c = :email');
        }
        
        // =====================================================
        // 4. ARCHIVE THRESHOLD (CHỈ KHI INTERACTION ĐÃ CLOSED)
        // =====================================================
        DateTime archiveThreshold;
        if (closeDt != null) {
            archiveThreshold = DateTime.now().addMonths(-3);
        }
        
        // =====================================================
        // 5. BUILD WHERE CONDITIONS (DYNAMIC)
        // =====================================================
        List<String> whereConditions = new List<String>();
        whereConditions.add('RecordType.DeveloperName != \'Interaction\'');
        whereConditions.add('Id != :recordId');
        whereConditions.add('(' + String.join(matchConditions, ' OR ') + ')');
        
        if (archiveThreshold != null) {
            whereConditions.add('ClosedDate >= :archiveThreshold');
        }
        
        // =====================================================
        // 6. FINAL SOQL
        // =====================================================
        String soql =
            'SELECT ' +
            '   Id, ' +
            '   FEC_Case_ID__c, ' +
            '   FEC_Case_Status__c, ' +
            '   FEC_SubCategory__c, ' +
            '   FEC_SubCategory__r.FEC_Code__c, ' +
            '   FEC_SubCategory__r.FEC_Name_VN__c, ' +
            '   FEC_SubCode__c, ' +
            '   FEC_SubCode__r.FEC_Code__c, ' +
            '   FEC_SubCode__r.FEC_Name_VN__c ' +
            'FROM Case ' +
            'WHERE ' + String.join(whereConditions, ' AND ') + ' ' +
            'ORDER BY FEC_Last_Updated_On__c DESC ' +
            'LIMIT 5';
        
        // =====================================================
        // 7. EXECUTE
        // =====================================================
        return Database.query(soql);
    }
    
    @AuraEnabled(cacheable=true)
    public static List<Case> getRelevantCasesViewAll(Id recordId) {
        
        // =====================================================
        // 1. LẤY INTERACTION HIỆN TẠI
        // =====================================================
        Case currentInteraction = getCurrentInteraction(recordId);
        if (currentInteraction == null) {
            return new List<Case>();
        }
        
        // =====================================================
        // 2. TÁCH BIẾN – RÕ NGHĨA
        // =====================================================
        String phone     = currentInteraction.FEC_Phone_Number__c;
        String email     = currentInteraction.FEC_Interaction_Email__c;
        DateTime closeDt = currentInteraction.ClosedDate;
        
        // Không có Phone & Email → không search
        if (String.isBlank(phone) && String.isBlank(email)) {
            return new List<Case>();
        }
        
        // =====================================================
        // 3. BUILD MATCH CONDITIONS (PHONE / EMAIL)
        // =====================================================
        List<String> matchConditions = new List<String>();
        
        if (String.isNotBlank(phone)) {
            matchConditions.add('FEC_Interaction__r.FEC_Phone_Number__c = :phone');
        }
        if (String.isNotBlank(email)) {
            matchConditions.add('FEC_Interaction__r.FEC_Interaction_Email__c = :email');
        }
        
        // =====================================================
        // 4. ARCHIVE THRESHOLD (CHỈ KHI INTERACTION ĐÃ CLOSED)
        // =====================================================
        DateTime archiveThreshold;
        if (closeDt != null) {
            archiveThreshold = DateTime.now().addMonths(-3);
        }
        
        // =====================================================
        // 5. BUILD WHERE CONDITIONS (DYNAMIC)
        // =====================================================
        List<String> whereConditions = new List<String>();
        whereConditions.add('RecordType.DeveloperName != \'Interaction\'');
        whereConditions.add('Id != :recordId');
        whereConditions.add('(' + String.join(matchConditions, ' OR ') + ')');
        
        if (archiveThreshold != null) {
            whereConditions.add('ClosedDate >= :archiveThreshold');
        }
        
        // =====================================================
        // 6. FINAL SOQL
        // =====================================================
        String soql =
            'SELECT ' +
            '   Id, ' +
            '   FEC_Case_ID__c, ' +
            '   FEC_Case_Status__c, ' +
            '   FEC_SubCategory__c, ' +
            '   FEC_SubCategory__r.FEC_Code__c, ' +
            '   FEC_SubCategory__r.FEC_Name_VN__c, ' +
            '   FEC_SubCode__c, ' +
            '   FEC_SubCode__r.FEC_Code__c, ' +
            '   FEC_SubCode__r.FEC_Name_VN__c ' +
            'FROM Case ' +
            'WHERE ' + String.join(whereConditions, ' AND ') + ' ' +
            'ORDER BY FEC_Last_Updated_On__c DESC' ;
        
        // =====================================================
        // 7. EXECUTE
        // =====================================================
        return Database.query(soql);
    }
    
    
    @AuraEnabled(cacheable=true)
    public static Integer getRelevantCasesViewAllCount(Id recordId) {
        
        // =====================================================
        // 1. LẤY INTERACTION HIỆN TẠI
        // =====================================================
        Case currentInteraction = getCurrentInteraction(recordId);
        if (currentInteraction == null) {
            return 0;
        }
        
        // =====================================================
        // 2. TÁCH BIẾN – RÕ NGHĨA
        // =====================================================
        String phone     = currentInteraction.FEC_Phone_Number__c;
        String email     = currentInteraction.FEC_Interaction_Email__c;
        DateTime closeDt = currentInteraction.ClosedDate;
        
        // Không có Phone & Email → không search
        if (String.isBlank(phone) && String.isBlank(email)) {
            return 0;
        }
        
        // =====================================================
        // 3. BUILD MATCH CONDITIONS (PHONE / EMAIL)
        // =====================================================
        List<String> matchConditions = new List<String>();
        
        if (String.isNotBlank(phone)) {
            matchConditions.add('FEC_Interaction__r.FEC_Phone_Number__c = :phone');
        }
        if (String.isNotBlank(email)) {
            matchConditions.add('FEC_Interaction__r.FEC_Interaction_Email__c = :email');
        }
        
        // =====================================================
        // 4. ARCHIVE THRESHOLD (CHỈ KHI INTERACTION ĐÃ CLOSED)
        // =====================================================
        DateTime archiveThreshold;
        if (closeDt != null) {
            archiveThreshold = DateTime.now().addMonths(-3);
        }
        
        // =====================================================
        // 5. BUILD WHERE CONDITIONS (DYNAMIC)
        // =====================================================
        List<String> whereConditions = new List<String>();
        whereConditions.add('RecordType.DeveloperName != \'Interaction\'');
        whereConditions.add('Id != :recordId');
        whereConditions.add('(' + String.join(matchConditions, ' OR ') + ')');
        
        if (archiveThreshold != null) {
            whereConditions.add('ClosedDate >= :archiveThreshold');
        }
        
        // =====================================================
        // 6. FINAL SOQL
        // =====================================================
        String soql =
            'SELECT COUNT()' +
            'FROM Case ' +
            'WHERE ' + String.join(whereConditions, ' AND ') ;
        
        // =====================================================
        // 7. EXECUTE
        // =====================================================
        return Database.countQuery(soql);
    }
    
    
    @AuraEnabled(cacheable=true)
    public static Case getCurrentInteraction(Id recordId) {
        return [
        SELECT FEC_Phone_Number__c,
               FEC_Interaction_Email__c,
               IsClosed,  FEC_Channel__c,
               ClosedDate
        FROM Case
        WHERE Id = :recordId
        LIMIT 1
    ];
    }
    
    @AuraEnabled(cacheable=true)
    public static List<FEC_Sensitive_Data__c> getSensitiveData(Id recordId) {
        try {
            List<FEC_Sensitive_Data__c> sensitiveDataList = [
                SELECT FEC_Case_ID__c, 
                       FEC_Section__c, 
                       Name, 
                       FEC_User__c, 
                       FEC_User_Role__c, 
                       CreatedDate 
                FROM FEC_Sensitive_Data__c
                WHERE FEC_Related_Case__c = :recordId
                ORDER BY CreatedDate DESC
                LIMIT 5
               
            ];
            return sensitiveDataList;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
    
    @AuraEnabled
    public static void resetViewMode(Id recordId, String viewMode) {
        if (recordId == null) return;
        
        update new Case(
            Id = recordId,
        FEC_Interaction_View_Mode__c = viewMode
            );
    }
    
    @AuraEnabled
    public static String getRecordTypeName(Id recordId) {
        if (recordId == null) return '';
        List<Case> caseList = [
            SELECT Id, RecordType.DeveloperName  FROM Case WHERE Id = :recordId
         ] ;
        
        string recordTypeName = caseList.isEmpty() ? null : caseList[0].RecordType.DeveloperName;
        return recordTypeName;
    }
}