force-app/main/default/objects/Case/fields/FEC_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>FEC_Account_Number__c</fullName>
    <label>Account Number</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/FEC_Account_or_Contract__c.field-meta.xml
<CustomField>
    <fullName>FEC_Account_or_Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account/ Contract Number</label>
    <referenceTo>FEC_Customer_History__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/FEC_CIF_Number__c.field-meta.xml
<CustomField>
    <fullName>FEC_CIF_Number__c</fullName>
    <description>Mã Cif của Kh (sau khi chọn sp thì hệ thống tự động cập nhật)</description>
    <label>CIF Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FEC_Customer_History__c/FEC_Customer_History__c.object-meta.xml
<CustomObject>
    <label>Customer History</label>
    <nameField>
        <label>Customer History Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Histories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FEC_Customer_History__c/fields/FEC_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>FEC_Account_Number__c</fullName>
    <description>Số tài khoản</description>
    <inlineHelpText>Số TK khách hàng</inlineHelpText>
    <label>Account Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FEC_Customer_History__c/fields/FEC_CIF_Number__c.field-meta.xml
<CustomField>
    <fullName>FEC_CIF_Number__c</fullName>
    <description>Số CIF</description>
    <label>CIF Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/FEC_AccountOrContractPicklistHanlder.cls
public without sharing class FEC_AccountOrContractPicklistHanlder {
    
    public class GetProductsListResponse {
        @AuraEnabled public String productType;
        @AuraEnabled public String accountContractNumber;
        @AuraEnabled public String productName;
    }
    
    @AuraEnabled(cacheable=true)
    public static String getInteractionAccountNumber(String caseId){
        try {
            
            Case interactionCase = [
            SELECT Id, FEC_Account_or_Contract__r.FEC_Account_Number__c,
                   FEC_Account_or_Contract__r.FEC_CIF_Number__c
            FROM Case
            WHERE Id = :caseId
            LIMIT 1
        ];
            
            Map<String, String> result = new Map<String, String>();
            
            if (interactionCase.FEC_Account_or_Contract__r != null) {
                result.put('accountNumber', interactionCase.FEC_Account_or_Contract__r.FEC_Account_Number__c);
                result.put('cifNumber', interactionCase.FEC_Account_or_Contract__r.FEC_CIF_Number__c);
            }
            
            return JSON.serialize(result);
            
        } catch (Exception e) {
            System.debug('Error getting account numbers: ' + e.getMessage());
            return JSON.serialize(new Map<String, String>());
        }
    }
    
    @AuraEnabled(cacheable=true)
    public static List<GetProductsListResponse> GetProductsListByCif(String cifNumber){
        
        
        if (String.isBlank(cifNumber)) {
            System.debug('CIF Number is blank');
            throw new AuraHandledException(String.format(System.Label.FEC_MSG_Param_Required, new List<String>{'CifNumber'}));
        }
        
        List<GetProductsListResponse> results = new List<GetProductsListResponse>();
        FEC_GetProductListCallout.CIF_GetProductsListResponse res =
            FEC_GetProductListCallout.callService(cifNumber);
        
        // Log tổng quan
        System.debug('=== CODE === ' + res.code);
        System.debug('=== DESCRIPTION === ' + res.description);
        System.debug('=== CIF === ' + res.cifNumber);
        
        if (res == null || res.products == null) {
            return results;
        }
        // Log từng product
        if (res.products != null) {
            for (FEC_GetProductListCallout.ProductInfo p : res.products) {
                System.debug('--- PRODUCT ---');
                System.debug('Type: ' + p.productType);
                System.debug('Contract: ' + p.contractNumber);
                System.debug('Account: ' + p.accountNumber);
                System.debug('Card: ' + p.cardNumber);
                System.debug('DealId: ' + p.dealId);
                
                GetProductsListResponse item = new GetProductsListResponse();
                item.productType = p.productType;
                if (p.productType == FEC_ConstantCommon.PRODUCT_TYPE_INSURANCE) {
                    item.accountContractNumber = p.contractNumber;
                    item.productType = p.productType;
                    item.productName = p.productName;
                } else if (p.productType == FEC_ConstantCommon.PRODUCT_TYPE_LOAN) {
                    item.accountContractNumber = p.contractNumber;
                    item.productType = p.productType;
                    item.productName = p.productName;
                } else if (p.productType == FEC_ConstantCommon.PRODUCT_TYPE_CARD) {
                    item.accountContractNumber = p.cardNumber;
                    item.productType = p.productType;
                    item.productName = p.productName;
                }
                results.add(item);
            }
        }
        return results;
        
    }
    
}