force-app/main/default/objects/Case/fields/FEC_Account_or_Contract__c.field-meta.xml
<CustomField>
    <fullName>FEC_Account_or_Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account/ Contract Number</label>
    <referenceTo>FEC_Customer_History__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/FEC_Channel__c.field-meta.xml
<CustomField>
    <fullName>FEC_Channel__c</fullName>
    <label>Channel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Channel</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/FEC_Created_On__c.field-meta.xml
<CustomField>
    <fullName>FEC_Created_On__c</fullName>
    <formula>CreatedDate</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Created On</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case/fields/FEC_External_Interaction_ID__c.field-meta.xml
<CustomField>
    <fullName>FEC_External_Interaction_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>External Interaction ID</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Case/fields/FEC_Final_Status__c.field-meta.xml
<CustomField>
    <fullName>FEC_Final_Status__c</fullName>
    <description>Trường final status chung của case và interaction được cập nhật khi trạng thái status chung hoặc người phụ trách có thay đổi</description>
    <formula>IF (NOT(ISBLANK(ArchiveStatus__c)), ArchiveStatus__c, 
    IF(
        ISPICKVAL(Status, &quot;Pending&quot;),
        &quot;Pending - &quot; &amp; FEC_Team__c,
        TEXT(Status)
    )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/FEC_ID_Search__c.field-meta.xml
<CustomField>
    <fullName>FEC_ID_Search__c</fullName>
    <description>Trường thông tin hứng giá trị ID của Case/Interaction gen ra từ apex code. sau đó sẽ được dùng để tạo ra trường ID hypelink</description>
    <externalId>true</externalId>
    <label>ID (Search)</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Case/fields/FEC_Interaction_Duration__c.field-meta.xml
<CustomField>
    <fullName>FEC_Interaction_Duration__c</fullName>
    <description>Khoảng thời gian diễn ra tương tác</description>
    <label>Interaction Duration</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case/fields/FEC_Interaction_Email__c.field-meta.xml
<CustomField>
    <fullName>FEC_Interaction_Email__c</fullName>
    <label>Interaction Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Case/fields/FEC_Interaction_End_On__c.field-meta.xml
<CustomField>
    <fullName>FEC_Interaction_End_On__c</fullName>
    <description>Thời điểm tương tác kết thúc</description>
    <label>Interaction End On</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case/fields/FEC_Interaction_Start_On__c.field-meta.xml
<CustomField>
    <fullName>FEC_Interaction_Start_On__c</fullName>
    <description>Thời điểm tương tác bắt đầu</description>
    <label>Interaction Start On</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case/fields/FEC_Interaction_Subchannel__c.field-meta.xml
<CustomField>
    <fullName>FEC_Interaction_Subchannel__c</fullName>
    <description>Kênh tương tác phụ</description>
    <label>Interaction Sub Channel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Inbound Call</fullName>
            </value>
            <value>
                <fullName>Outbound Call</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/FEC_National_ID_Passport_ID__c.field-meta.xml
<CustomField>
    <fullName>FEC_National_ID_Passport_ID__c</fullName>
    <externalId>true</externalId>
    <label>National ID/ Passport ID</label>
    <length>12</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Case/fields/FEC_Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>FEC_Phone_Number__c</fullName>
    <description>Số điện thoại khách hàng đã liên hệ</description>
    <label>Interaction Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Case/fields/FEC_Sub_Channel__c.field-meta.xml
<CustomField>
    <fullName>FEC_Sub_Channel__c</fullName>
    <label>Sub-channel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Facebook</fullName>
            </value>
            <value>
                <fullName>Zalo</fullName>
            </value>
            <value>
                <fullName>Webchat</fullName>
            </value>
            <value>
                <fullName>Mobile App Chat</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Inbound Call</fullName>
            </value>
            <value>
                <fullName>Outbound Call</fullName>
            </value>
            <value>
                <fullName>Incoming Email</fullName>
            </value>
            <value>
                <fullName>Outgoing Email</fullName>
            </value>
            <value>
                <fullName>F2F</fullName>
            </value>
            <value>
                <fullName>Letter</fullName>
            </value>
            <value>
                <fullName>Other External Interaction</fullName>
            </value>
            <value>
                <fullName>Internal Email</fullName>
            </value>
            <value>
                <fullName>Internal Task</fullName>
            </value>
            <value>
                <fullName>PR/ MKT</fullName>
            </value>
            <value>
                <fullName>SBV</fullName>
            </value>
            <value>
                <fullName>EA</fullName>
            </value>
            <value>
                <fullName>VPBank</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Interaction.recordType-meta.xml
<RecordType>
    <fullName>Interaction</fullName>
    <active>true</active>
    <businessProcess>Interaction Process</businessProcess>
    <label>Interaction</label>
</RecordType>

force-app/main/default/objects/FEC_Channel__c/FEC_Channel__c.object-meta.xml
<CustomObject>
    <description>Là tính năng Channels Library thuộc module Business Configuration Tools trong Salesforce tại FEC. Channels Library dùng để liệt kê và quản lý các kênh tích hợp, hỗ trợ hệ thống bên ngoài truy xuất dữ liệu (Master Data, Nature of Case, trạng thái Case…).
Thông qua MyCase API, các hệ thống như Mobile App, Vymo, Pega có thể tạo Case trên New CSM; để thực hiện thao tác này, hệ thống cần được khai báo Channel tương ứng trong Channels Library.</description>
    <label>Channels</label>
    <nameField>
        <label>Channel English Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Channels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FEC_Customer_History__c/FEC_Customer_History__c.object-meta.xml
<CustomObject>
    <label>Customer History</label>
    <nameField>
        <label>Customer History Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Histories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FEC_Customer_History__c/fields/FEC_National_ID_Passport_ID__c.field-meta.xml
<CustomField>
    <fullName>FEC_National_ID_Passport_ID__c</fullName>
    <description>Căn cước/ Hộ chiếu</description>
    <inlineHelpText>CCCD/CMND của khách hàng</inlineHelpText>
    <label>National ID/ Passport ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FEC_Customer_History__c/fields/FEC_Primary_Phone__c.field-meta.xml
<CustomField>
    <fullName>FEC_Primary_Phone__c</fullName>
    <description>Số điện thoại chính</description>
    <label>Primary Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/FEC_Customer_History__c/fields/FEC_Sub_Channel__c.field-meta.xml
<CustomField>
    <fullName>FEC_Sub_Channel__c</fullName>
    <description>Kênh bán phụ</description>
    <label>Sub Channel</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Channel.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Inbound</fullName>
    </customValue>
    <customValue>
        <fullName>Outbound</fullName>
    </customValue>
    <customValue>
        <fullName>Chat</fullName>
    </customValue>
    <customValue>
        <fullName>Email</fullName>
    </customValue>
    <customValue>
        <fullName>F2F</fullName>
    </customValue>
    <customValue>
        <fullName>Letter</fullName>
    </customValue>
    <customValue>
        <fullName>External</fullName>
    </customValue>
    <customValue>
        <fullName>Internal</fullName>
    </customValue>
    <customValue>
        <fullName>Social &amp; Media</fullName>
    </customValue>
    <customValue>
        <fullName>Research</fullName>
    </customValue>
    <masterLabel>Channel</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/FEC_InteractionController.cls
/**
 * Class Description: Controller class cung cấp các phương thức xử lý Interaction cho LWC
 * @created  : 2026/01/03 Toannd61
 * @modified :    
 */
public with sharing class FEC_InteractionController {
    
    // @AuraEnabled(cacheable=true)
    // public static List<Case> getAllInteractions(String nationalID, String primaryPhone) {
    //     try {
    //         return [
    //             SELECT Id, 
    //                 CaseNumber, FEC_ID_Search__c, FEC_Channel__c, FEC_Sub_Channel__c,
    //                    FEC_Interaction_Start_On__c, FEC_Interaction_End_On__c,
    //                    FEC_Interaction_Duration__c, CreatedBy.Name, CreatedBy.Id, FEC_Created_On__c,
    //                    Type, RecordType.Name, FEC_Final_Status__c, FEC_External_Interaction_ID__c,
    //                    FEC_Phone_Number__c, FEC_Interaction_Email__c
    //             FROM Case
    //             WHERE RecordType.DeveloperName = 'Interaction'
    //             AND FEC_National_ID_Passport_ID__c = :nationalID
    //             AND FEC_Phone_Number__c = :primaryPhone
    //             ORDER BY FEC_Created_On__c DESC
    //             LIMIT 10
    //         ];
    //     } catch (Exception e) {
    //         throw new AuraHandledException('Error retrieving interactions: ' + e.getMessage());
    //     }
    // }

    /**
     * Method Description: Lấy danh sách Interaction theo National ID và Primary Phone
     * @param nationalId National ID của khách hàng
     * @param primaryPhone Số điện thoại chính của khách hàng
     * @return List<Case> Danh sách Interaction
     * @created: 2026/01/03 Toannd61
     * @modified:  
     */
    @AuraEnabled
    public static List<Case> getInteraction(String nationalId, String primaryPhone) {
        try {
            // Query interaction records from Case object
            return [
                SELECT Id, 
                FEC_ID_Search__c, 
                FEC_Channel__c, 
                FEC_Interaction_Subchannel__c, 
                FEC_Interaction_Start_On__c,
                CreatedById,
                CreatedBy.Name,
                FEC_Interaction_Duration__c,
                FEC_Interaction_End_On__c,
                Status,
                FEC_External_Interaction_ID__c,
                FEC_Phone_Number__c,
                FEC_Interaction_Email__c
                FROM Case
                WHERE RecordType.DeveloperName = :FEC_ConstantCommon.CASE_INTERACTION_RECORD_TYPE_DEV_NAME
                AND FEC_Account_or_Contract__r.FEC_National_ID_Passport_ID__c = :nationalId
                AND FEC_Account_or_Contract__r.FEC_Primary_Phone__c = :primaryPhone
                ORDER BY FEC_Interaction_Start_On__c DESC
                LIMIT 10
            ];
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
    
    
}