force-app/main/default/objects/Case/fields/FEC_Account_or_Contract__c.field-meta.xml
<CustomField>
    <fullName>FEC_Account_or_Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account/ Contract Number</label>
    <referenceTo>FEC_Customer_History__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/FEC_Adjusted_Amount__c.field-meta.xml
<CustomField>
    <fullName>FEC_Adjusted_Amount__c</fullName>
    <description>Người dùng nhập số tiền cần điều chỉnh</description>
    <label>Adjusted Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case/fields/FEC_Bill_Amount__c.field-meta.xml
<CustomField>
    <fullName>FEC_Bill_Amount__c</fullName>
    <description>Tự động điền Payment Amount của giao dịch được chọn và User không thể điều chỉnh.</description>
    <label>Bill Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case/fields/FEC_Contract_Number__c.field-meta.xml
<CustomField>
    <fullName>FEC_Contract_Number__c</fullName>
    <label>Contract Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/FEC_Correct_Contract_Number__c.field-meta.xml
<CustomField>
    <fullName>FEC_Correct_Contract_Number__c</fullName>
    <description>Số hợp đồng đúng. Hiển thị gợi ý tất cả số HĐ/ TK của KH tại FEC để User chọn 1 (kể cả số HĐ đã chọn ở mục Incorrect Contract Number).</description>
    <label>Correct Contract Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/FEC_ID_Search__c.field-meta.xml
<CustomField>
    <fullName>FEC_ID_Search__c</fullName>
    <description>Trường thông tin hứng giá trị ID của Case/Interaction gen ra từ apex code. sau đó sẽ được dùng để tạo ra trường ID hypelink</description>
    <externalId>true</externalId>
    <label>ID (Search)</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Case/fields/FEC_Incorrect_Contract_Number__c.field-meta.xml
<CustomField>
    <fullName>FEC_Incorrect_Contract_Number__c</fullName>
    <description>Trường cho phép user nhập số HĐ sai và hệ thống sẽ hiển thị dropdown list của các số HĐ liên quan cho user chọn. Sau khi chọn sẽ trả về payment history tương ứng với số HĐ đó</description>
    <label>Incorrect Contract Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/FEC_Incorrect_Payment_Adj_Rows__c.field-meta.xml
<CustomField>
    <fullName>FEC_Incorrect_Payment_Adj_Rows__c</fullName>
    <description>JSON array of incorrect-payment adjustment rows (correctContract, adjustedAmount). Row 1 is also on FEC_Correct_Contract_Number__c / FEC_Adjusted_Amount__c.</description>
    <label>Incorrect Payment Adjustment Rows</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/FEC_Input_Correct_Contract_Number__c.field-meta.xml
<CustomField>
    <fullName>FEC_Input_Correct_Contract_Number__c</fullName>
    <description>Người dùng nhập tay thủ công số HĐ đúng nằm ngoài danh sách được lưu trong hệ thống</description>
    <label>Input Correct Contract Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/FEC_Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>FEC_Payment_Method__c</fullName>
    <description>Hình thức thanh toán của HĐ user nhập</description>
    <label>Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bank Transfers</fullName>
            </value>
            <value>
                <fullName>Other Channels</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/FEC_Selected_Payment_History__c.field-meta.xml
<CustomField>
    <fullName>FEC_Selected_Payment_History__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Payment History record selected on Incorrect Payment form.</description>
    <label>Selected Payment History</label>
    <referenceTo>FEC_Payment_History__c</referenceTo>
    <relationshipLabel>Cases Selected Payment</relationshipLabel>
    <relationshipName>Cases_Selected_Payment</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/FEC_SubCode__c.field-meta.xml
<CustomField>
    <fullName>FEC_SubCode__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Thông tin danh mục con</description>
    <label>Updated Sub Code</label>
    <referenceTo>FEC_Sub_Code__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FEC_API_Setting__c/FEC_API_Setting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>FEC API Setting</label>
</CustomObject>

force-app/main/default/objects/FEC_API_Setting__c/fields/FEC_Call_Mock__c.field-meta.xml
<CustomField>
    <fullName>FEC_Call_Mock__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Call Mock</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FEC_API_Setting__c/fields/FEC_Endpoint__c.field-meta.xml
<CustomField>
    <fullName>FEC_Endpoint__c</fullName>
    <label>Endpoint</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FEC_API_Setting__c/fields/FEC_Enviroment__c.field-meta.xml
<CustomField>
    <fullName>FEC_Enviroment__c</fullName>
    <label>Enviroment</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FEC_Customer_History__c/FEC_Customer_History__c.object-meta.xml
<CustomObject>
    <label>Customer History</label>
    <nameField>
        <label>Customer History Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Histories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FEC_Customer_History__c/fields/FEC_Case__c.field-meta.xml
<CustomField>
    <fullName>FEC_Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Customer Histories</relationshipLabel>
    <relationshipName>Customer_Histories</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FEC_Customer_History__c/fields/FEC_Contract_Number__c.field-meta.xml
<CustomField>
    <fullName>FEC_Contract_Number__c</fullName>
    <description>Số hợp đồng</description>
    <label>Contract Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FEC_Incorrect_Payment_Info__c/FEC_Incorrect_Payment_Info__c.object-meta.xml
<CustomObject>
    <label>Incorrect Payment Info</label>
    <nameField>
        <displayFormat>IPI - {0}</displayFormat>
        <label>Incorrect Payment Info Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Incorrect Payment Info</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FEC_Incorrect_Payment_Info__c/fields/FEC_Adjusted_Amount__c.field-meta.xml
<CustomField>
    <fullName>FEC_Adjusted_Amount__c</fullName>
    <label>Adjusted Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FEC_Incorrect_Payment_Info__c/fields/FEC_Case__c.field-meta.xml
<CustomField>
    <fullName>FEC_Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Incorrect Payment Info</relationshipLabel>
    <relationshipName>Incorrect_Payment_Info</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FEC_Incorrect_Payment_Info__c/fields/FEC_Correct_Account_Contract__c.field-meta.xml
<CustomField>
    <fullName>FEC_Correct_Account_Contract__c</fullName>
    <label>Correct Account Contract</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FEC_Nature_of_Case__c/FEC_Nature_of_Case__c.object-meta.xml
<CustomObject>
    <description>Là bảng dữ liệu chứa bộ Nature of Case</description>
    <label>Nature of Cases</label>
    <nameField>
        <displayFormat>NOC-{0}</displayFormat>
        <label>Nature of Case Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Nature of Cases</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/FEC_Nature_of_Case__c/fields/FEC_Active__c.field-meta.xml
<CustomField>
    <fullName>FEC_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Trạng thái của bộ NOC</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FEC_Nature_of_Case__c/fields/FEC_Sub_Code__c.field-meta.xml
<CustomField>
    <fullName>FEC_Sub_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Thông tin danh mục con</description>
    <label>Sub Code</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>FEC_Sub_Code__c.FEC_Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>FEC_Sub_Code__c</referenceTo>
    <relationshipLabel>Nature of Cases</relationshipLabel>
    <relationshipName>Nature_of_Case</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FEC_Payment_History__c/FEC_Payment_History__c.object-meta.xml
<CustomObject>
    <label>Payment History</label>
    <nameField>
        <displayFormat>PHN - {0}</displayFormat>
        <label>Payment History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment History</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FEC_Payment_History__c/fields/FEC_Customer_History__c.field-meta.xml
<CustomField>
    <fullName>FEC_Customer_History__c</fullName>
    <label>Customer History</label>
    <referenceTo>FEC_Customer_History__c</referenceTo>
    <relationshipLabel>Payment History</relationshipLabel>
    <relationshipName>Payment_History</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FEC_Payment_History__c/fields/FEC_Payment_Amount__c.field-meta.xml
<CustomField>
    <fullName>FEC_Payment_Amount__c</fullName>
    <label>Payment Amount</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FEC_Payment_History__c/fields/FEC_Payment_No__c.field-meta.xml
<CustomField>
    <fullName>FEC_Payment_No__c</fullName>
    <label>Payment No.</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FEC_Sub_Code__c/FEC_Sub_Code__c.object-meta.xml
<CustomObject>
    <label>FEC_Sub Code</label>
    <nameField>
        <label>FEC_Sub Code Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FEC_Sub Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FEC_Sub_Code__c/fields/FEC_Code__c.field-meta.xml
<CustomField>
    <fullName>FEC_Code__c</fullName>
    <description>Mã Code danh mục con</description>
    <label>Code</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/FEC_IncorrectPaymentController_Test.cls
@IsTest
private class FEC_IncorrectPaymentController_Test {

    private static User adminUser() {
        return [
            SELECT Id
            FROM User
            WHERE Profile.Name = 'System Administrator' AND IsActive = TRUE
            LIMIT 1
        ];
    }

    @TestSetup
    static void setup() {
        String suffix = String.valueOf(System.currentTimeMillis());
        FEC_API_Setting__c apiSetting = new FEC_API_Setting__c(
            FEC_Enviroment__c = FEC_ConstantCommon.ENVIROMENT_NON_PRODUCTION,
            FEC_Call_Mock__c = false,
            FEC_Endpoint__c = 'https://test.com/api'
        );
        insert apiSetting;
        FEC_CaseTriggerHandler.isExecuting = true;
        try {
            insert new Case(
                Subject = 'FEC_IncorrectPaymentController_Test',
                Status = 'New',
                FEC_ID_Search__c = 'INCP-' + suffix
            );
        } finally {
            FEC_CaseTriggerHandler.isExecuting = false;
        }
    }

    @IsTest
    static void testGetPaymentHistoryFromSOAP_Success() {
        Case c = [SELECT Id FROM Case LIMIT 1];
        Test.startTest();
        try {
            FEC_IncorrectPaymentController.getPaymentHistoryFromSOAP(c.Id, 'CON123');
        } catch (Exception e) {
            System.assert(true, 'Expected without SOAP mock: ' + e.getMessage());
        }
        Test.stopTest();
    }

    @IsTest
    static void testSaveAdjustment_Success() {
        Case c = [SELECT Id FROM Case LIMIT 1];

        List<FEC_IncorrectPaymentController.AdjustmentDTO> adjs =
            new List<FEC_IncorrectPaymentController.AdjustmentDTO>();
        FEC_IncorrectPaymentController.AdjustmentDTO adj =
            new FEC_IncorrectPaymentController.AdjustmentDTO();
        adj.correctContract = '1';
        adj.adjustedAmount = 1000;
        adjs.add(adj);

        System.runAs(adminUser()) {
            Test.startTest();
            FEC_IncorrectPaymentController.saveAdjustment(
                c.Id,
                'CON_BAD',
                'Bank Transfers',
                '2026-05-25',
                1000,
                adjs
            );
            Test.stopTest();

            Case updatedCase = [
                SELECT FEC_Adjusted_Amount__c,
                    FEC_Incorrect_Contract_Number__c,
                    FEC_Payment_Method__c,
                    FEC_Correct_Contract_Number__c,
                    FEC_Input_Correct_Contract_Number__c,
                    FEC_Bill_Amount__c
                FROM Case
                WHERE Id = :c.Id
            ];
            System.assertEquals(1000, updatedCase.FEC_Adjusted_Amount__c);
            System.assertEquals('CON_BAD', updatedCase.FEC_Incorrect_Contract_Number__c);
            System.assertEquals('Bank Transfers', updatedCase.FEC_Payment_Method__c);
            System.assertEquals('1', updatedCase.FEC_Correct_Contract_Number__c);
            System.assertEquals('1', updatedCase.FEC_Input_Correct_Contract_Number__c);
            System.assertEquals(1000, updatedCase.FEC_Bill_Amount__c);

            List<FEC_Incorrect_Payment_Info__c> infoRows = [
                SELECT FEC_Adjusted_Amount__c, FEC_Correct_Account_Contract__c
                FROM FEC_Incorrect_Payment_Info__c
                WHERE FEC_Case__c = :c.Id
            ];
            System.assertEquals(1, infoRows.size());
            System.assertEquals(1000, infoRows[0].FEC_Adjusted_Amount__c);
            System.assertEquals('1', infoRows[0].FEC_Correct_Account_Contract__c);
        }
    }

    @IsTest
    static void testGetSubCodeConfig() {
        Case c = [SELECT Id FROM Case LIMIT 1];

        Test.startTest();
        FEC_IncorrectPaymentController.SubCodeConfigDTO dto =
            FEC_IncorrectPaymentController.getSubCodeConfig(c.Id);
        Test.stopTest();

        System.assertNotEquals(null, dto);
    }

    @IsTest
    static void testGetPaymentHistoryFromSOAP_BlankContract() {
        Case c = [SELECT Id FROM Case LIMIT 1];
        Test.startTest();
        List<FEC_IncorrectPaymentController.PaymentDTO> empty =
            FEC_IncorrectPaymentController.getPaymentHistoryFromSOAP(c.Id, '');
        Test.stopTest();

        System.assertEquals(0, empty.size());
    }

    @IsTest
    static void testGetPaymentHistoryFromSOAP_WithMock() {
        Case c = [SELECT Id FROM Case LIMIT 1];
        FEC_Customer_History__c hist = new FEC_Customer_History__c(
            Name = 'IPP-PH-TEST',
            FEC_Contract_Number__c = '20170108-0005091',
            FEC_Case__c = c.Id
        );
        insert hist;
        update new Case(Id = c.Id, FEC_Account_or_Contract__c = hist.Id);
        Test.setMock(HttpCalloutMock.class, new MockLoanSecInfoSuccess());

        Test.startTest();
        List<FEC_IncorrectPaymentController.PaymentDTO> payments =
            FEC_IncorrectPaymentController.getPaymentHistoryFromSOAP(c.Id, '20170108-0005091');
        Test.stopTest();

        System.assertEquals(1, payments.size());
        System.assertEquals('1', payments[0].paymentNo);
        List<FEC_Payment_History__c> saved = [
            SELECT Id, FEC_Payment_No__c, FEC_Payment_Amount__c, FEC_Customer_History__c
            FROM FEC_Payment_History__c
            WHERE FEC_Customer_History__c = :hist.Id
        ];
        System.assertEquals(1, saved.size());
        System.assertEquals(1, saved[0].FEC_Payment_No__c);
        System.assertEquals(620.00, saved[0].FEC_Payment_Amount__c);
    }

    @IsTest
    static void testPicklistAndContractOptions() {
        Case c = [SELECT Id FROM Case LIMIT 1];

        Test.startTest();
        List<FEC_CommonUltils.PicklistOption> paymentMethods =
            FEC_IncorrectPaymentController.getPaymentMethodOptions();
        List<FEC_CommonUltils.PicklistOption> correctContracts =
            FEC_IncorrectPaymentController.getCorrectContractOptions(c.Id);
        List<FEC_CommonUltils.PicklistOption> incorrectContracts =
            FEC_IncorrectPaymentController.getIncorrectContractOptions(c.Id);
        List<FEC_CommonUltils.PicklistOption> nullCase =
            FEC_IncorrectPaymentController.getIncorrectContractOptions(null);
        Test.stopTest();

        System.assertNotEquals(null, paymentMethods);
        System.assertNotEquals(null, correctContracts);
        System.assertNotEquals(null, incorrectContracts);
        System.assertEquals(0, nullCase.size());
    }

    @IsTest
    static void testGetLoanContractOptionsFromApi_WithMock() {
        Case c = [SELECT Id FROM Case LIMIT 1];
        update new Case(
            Id = c.Id,
            FEC_Contract_Number__c = '20170108-0005091'
        );
        Test.setMock(HttpCalloutMock.class, new MockGetCustomerListSuccess());

        Test.startTest();
        List<FEC_CommonUltils.PicklistOption> options =
            FEC_IncorrectPaymentController.getLoanContractOptionsFromApi(c.Id);
        Test.stopTest();

        System.assert(!options.isEmpty(), 'Should include contract options.');
        Set<String> values = new Set<String>();
        for (FEC_CommonUltils.PicklistOption opt : options) {
            if (opt != null && String.isNotBlank(opt.value)) {
                values.add(opt.value);
            }
        }
        System.assert(values.contains('20170108-0005091'), 'Should include contract from Case.');
        System.assert(values.contains('20170108-0005092'), 'Should include ContractNumber from GetCustomerList Applications.');
    }

    @IsTest
    static void testSaveAdjustmentDraft() {
        Case c = [SELECT Id FROM Case LIMIT 1];

        System.runAs(adminUser()) {
            Test.startTest();
            FEC_IncorrectPaymentController.saveAdjustmentDraft(
                c.Id,
                'CON_DRAFT',
                'Bank Transfers',
                '2026-05-25',
                500,
                '1',
                500
            );
            Test.stopTest();

            Case updated = [
                SELECT FEC_Incorrect_Contract_Number__c, FEC_Bill_Amount__c
                FROM Case
                WHERE Id = :c.Id
            ];
            System.assertEquals('CON_DRAFT', updated.FEC_Incorrect_Contract_Number__c);
            System.assertEquals(500, updated.FEC_Bill_Amount__c);
        }
    }

    @IsTest
    static void testSaveAdjustment_ValidationErrors() {
        Case c = [SELECT Id FROM Case LIMIT 1];

        Test.startTest();
        try {
            FEC_IncorrectPaymentController.saveAdjustment(null, 'X', 'Bank Transfers', '2026-05-25', 100, null);
            System.assert(false, 'Null case should throw.');
        } catch (AuraHandledException e) {
            System.assert(true);
        }

        try {
            FEC_IncorrectPaymentController.saveAdjustment(
                c.Id,
                'CON_BAD',
                '',
                '2026-05-25',
                100,
                new List<FEC_IncorrectPaymentController.AdjustmentDTO>()
            );
            System.assert(false, 'Empty adjustments should throw.');
        } catch (AuraHandledException e2) {
            System.assert(true);
        }
        Test.stopTest();
    }

    @IsTest
    static void testGetSubCodeConfig_WithAdjustmentRowsJson() {
        Case c = [SELECT Id FROM Case LIMIT 1];
        List<FEC_IncorrectPaymentController.AdjustmentDTO> adjs =
            new List<FEC_IncorrectPaymentController.AdjustmentDTO>();
        FEC_IncorrectPaymentController.AdjustmentDTO adj =
            new FEC_IncorrectPaymentController.AdjustmentDTO();
        adj.correctContract = '1';
        adj.adjustedAmount = 250;
        adjs.add(adj);

        update new Case(
            Id = c.Id,
            FEC_Incorrect_Payment_Adj_Rows__c = JSON.serialize(adjs)
        );

        Test.startTest();
        FEC_IncorrectPaymentController.SubCodeConfigDTO dto =
            FEC_IncorrectPaymentController.getSubCodeConfig(c.Id);
        FEC_IncorrectPaymentController.SubCodeConfigDTO nullDto =
            FEC_IncorrectPaymentController.getSubCodeConfig(null);
        Test.stopTest();

        System.assertNotEquals(null, dto.adjustmentRows);
        System.assertEquals(1, dto.adjustmentRows.size());
        System.assertNotEquals(null, nullDto);
    }

    @IsTest
    static void testGetPaymentHistoryFromSOAP_FailureResponse() {
        Case c = [SELECT Id FROM Case LIMIT 1];
        Test.setMock(HttpCalloutMock.class, new MockLoanSecInfoFailure());

        Test.startTest();
        try {
            FEC_IncorrectPaymentController.getPaymentHistoryFromSOAP(c.Id, 'CON-FAIL');
            System.assert(false, 'Non-success SOAP response should throw.');
        } catch (AuraHandledException e) {
            System.assert(true);
        }
        Test.stopTest();
    }

    @IsTest
    static void testGetPaymentHistoryFromSOAP_EmptyHistories() {
        Case c = [SELECT Id FROM Case LIMIT 1];
        Test.setMock(HttpCalloutMock.class, new MockLoanSecInfoEmptyHistory());

        Test.startTest();
        try {
            FEC_IncorrectPaymentController.getPaymentHistoryFromSOAP(c.Id, 'CON-EMPTY');
            System.assert(false, 'Empty payment histories should throw.');
        } catch (AuraHandledException e) {
            System.assert(true);
        }
        Test.stopTest();
    }

    @IsTest
    static void testSaveAdjustment_AmountMismatch() {
        Case c = [SELECT Id FROM Case LIMIT 1];
        List<FEC_IncorrectPaymentController.AdjustmentDTO> adjs =
            new List<FEC_IncorrectPaymentController.AdjustmentDTO>();
        FEC_IncorrectPaymentController.AdjustmentDTO adj =
            new FEC_IncorrectPaymentController.AdjustmentDTO();
        adj.correctContract = '1';
        adj.adjustedAmount = 500;
        adjs.add(adj);

        Test.startTest();
        try {
            FEC_IncorrectPaymentController.saveAdjustment(
                c.Id,
                'CON_BAD',
                'Bank Transfers',
                '2026-05-25',
                1000,
                adjs
            );
            System.assert(false, 'Sum adjusted amount mismatch should throw.');
        } catch (AuraHandledException e) {
            System.assert(true);
        }
        Test.stopTest();
    }

    @IsTest
    static void testSaveSelectedPaymentHistory() {
        Case c = [SELECT Id FROM Case LIMIT 1];
        FEC_Customer_History__c hist = new FEC_Customer_History__c(
            Name = 'IPP-SEL-PH',
            FEC_Contract_Number__c = '20170108-0005091',
            FEC_Case__c = c.Id
        );
        insert hist;
        FEC_Payment_History__c ph = new FEC_Payment_History__c(
            FEC_Customer_History__c = hist.Id,
            FEC_Payment_No__c = 1,
            FEC_Payment_Amount__c = 100
        );
        insert ph;

        System.runAs(adminUser()) {
            Test.startTest();
            FEC_IncorrectPaymentController.saveSelectedPaymentHistory(c.Id, ph.Id);
            FEC_IncorrectPaymentController.saveSelectedPaymentHistory(c.Id, null);
            Test.stopTest();

            Case updated = [
                SELECT FEC_Selected_Payment_History__c
                FROM Case
                WHERE Id = :c.Id
            ];
            System.assertEquals(null, updated.FEC_Selected_Payment_History__c);
        }
    }

    @IsTest
    static void testGetIncorrectContractOptions_WithContracts() {
        Case c = [SELECT Id FROM Case LIMIT 1];
        update new Case(
            Id = c.Id,
            FEC_Contract_Number__c = 'CON-PRIMARY',
            FEC_Incorrect_Contract_Number__c = 'CON-INCORRECT'
        );

        Test.startTest();
        List<FEC_CommonUltils.PicklistOption> options =
            FEC_IncorrectPaymentController.getIncorrectContractOptions(c.Id);
        Test.stopTest();

        System.assert(options.size() >= 2, 'Should include contract numbers from Case fields.');
    }

    @IsTest
    static void testGetSubCodeConfig_WithSubCode() {
        FEC_Sub_Code__c subCode = new FEC_Sub_Code__c(
            Name = 'Incorrect Payment',
            FEC_Code__c = 'IP01',
            FEC_Active__c = true
        );
        insert subCode;
        insert new FEC_Nature_of_Case__c(FEC_Sub_Code__c = subCode.Id);

        Case c = [SELECT Id FROM Case LIMIT 1];
        update new Case(Id = c.Id, FEC_SubCode__c = subCode.Id);

        Test.startTest();
        FEC_IncorrectPaymentController.SubCodeConfigDTO dto =
            FEC_IncorrectPaymentController.getSubCodeConfig(c.Id);
        Test.stopTest();

        System.assertEquals('IP01', dto.subCode);
    }

    @IsTest
    static void testSaveAdjustment_InvalidRowsOnly() {
        Case c = [SELECT Id FROM Case LIMIT 1];
        List<FEC_IncorrectPaymentController.AdjustmentDTO> adjs =
            new List<FEC_IncorrectPaymentController.AdjustmentDTO>();
        FEC_IncorrectPaymentController.AdjustmentDTO partial =
            new FEC_IncorrectPaymentController.AdjustmentDTO();
        partial.correctContract = '1';
        adjs.add(partial);

        Test.startTest();
        try {
            FEC_IncorrectPaymentController.saveAdjustment(
                c.Id,
                'CON_BAD',
                'Bank Transfers',
                '2026-05-25',
                null,
                adjs
            );
            System.assert(false, 'Rows without adjusted amount should throw.');
        } catch (AuraHandledException e) {
            System.assert(true);
        }
        Test.stopTest();
    }

    private class MockGetCustomerListSuccess implements HttpCalloutMock {
        public HttpResponse respond(HttpRequest req) {
            HttpResponse res = new HttpResponse();
            res.setStatusCode(200);
            res.setBody(
                '<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">' +
                '<soapenv:Body><cif:GetCustomerListResponse xmlns:cif="http://fecredit.com.vn/CIF_CustomerSearch">' +
                '<Sys><Code>1</Code><Description>DATA FOUND</Description></Sys><Count>1</Count>' +
                '<Customers><Customer><Applications><Application>' +
                '<ContractNumber>20170108-0005092</ContractNumber><AccountNumber>0001500100000030081</AccountNumber>' +
                '</Application></Applications></Customer></Customers>' +
                '</cif:GetCustomerListResponse></soapenv:Body></soapenv:Envelope>'
            );
            return res;
        }
    }

    private class MockLoanSecInfoEmptyHistory implements HttpCalloutMock {
        public HttpResponse respond(HttpRequest req) {
            HttpResponse res = new HttpResponse();
            res.setStatusCode(200);
            res.setBody(
                '<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">' +
                '<soapenv:Body><GetLoanSecInfoResponse><Sys><Code>1</Code></Sys>' +
                '<LoanSecInfo><PaymentHistories/></LoanSecInfo></GetLoanSecInfoResponse></soapenv:Body></soapenv:Envelope>'
            );
            return res;
        }
    }

    private class MockLoanSecInfoSuccess implements HttpCalloutMock {
        public HttpResponse respond(HttpRequest req) {
            HttpResponse res = new HttpResponse();
            res.setStatusCode(200);
            res.setBody(
                '<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">' +
                '<soapenv:Body><GetLoanSecInfoResponse><Sys><Code>1</Code></Sys>' +
                '<LoanSecInfo><PaymentHistories><PaymentHistory>' +
                '<BookingDate>2026-03-01</BookingDate><ValueDate>2026-03-02</ValueDate>' +
                '<AmountOfMoney>620.00</AmountOfMoney><ChkNo>CHK001</ChkNo>' +
                '</PaymentHistory></PaymentHistories></LoanSecInfo></GetLoanSecInfoResponse></soapenv:Body></soapenv:Envelope>'
            );
            return res;
        }
    }

    private class MockLoanSecInfoFailure implements HttpCalloutMock {
        public HttpResponse respond(HttpRequest req) {
            HttpResponse res = new HttpResponse();
            res.setStatusCode(200);
            res.setBody(
                '<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">' +
                '<soapenv:Body><GetLoanSecInfoResponse><Sys><Code>0</Code>' +
                '<Description>Loan not found</Description></Sys></GetLoanSecInfoResponse></soapenv:Body></soapenv:Envelope>'
            );
            return res;
        }
    }
}