force-app/main/default/objects/Case/fields/FEC_Account_or_Contract__c.field-meta.xml
<CustomField>
    <fullName>FEC_Account_or_Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account/ Contract Number</label>
    <referenceTo>FEC_Customer_History__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/FEC_Interaction__c.field-meta.xml
<CustomField>
    <fullName>FEC_Interaction__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Trường lookup hiển thị Interaction sinh ra Case</description>
    <label>Interaction ID</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Cases (Interaction)</relationshipLabel>
    <relationshipName>Cases1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/FEC_SubCode__c.field-meta.xml
<CustomField>
    <fullName>FEC_SubCode__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Thông tin danh mục con</description>
    <label>Updated Sub Code</label>
    <referenceTo>FEC_Sub_Code__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FEC_Address_Info__c/FEC_Address_Info__c.object-meta.xml
<CustomObject>
    <label>Address Info</label>
    <nameField>
        <label>Address Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Address Info</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FEC_Address_Info__c/fields/FEC_Address__c.field-meta.xml
<CustomField>
    <fullName>FEC_Address__c</fullName>
    <description>Địa chỉ</description>
    <label>Address</label>
    <length>1024</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/FEC_Address_Info__c/fields/FEC_Address_Type__c.field-meta.xml
<CustomField>
    <fullName>FEC_Address_Type__c</fullName>
    <description>Loại địa chỉ</description>
    <label>Address Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Current Address</fullName>
            </value>
            <value>
                <fullName>Office Address</fullName>
            </value>
            <value>
                <fullName>Permanent Address</fullName>
            </value>
            <value>
                <fullName>Temporary Address</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FEC_Address_Info__c/fields/FEC_Customer_History__c.field-meta.xml
<CustomField>
    <fullName>FEC_Customer_History__c</fullName>
    <label>Customer History</label>
    <referenceTo>FEC_Customer_History__c</referenceTo>
    <relationshipLabel>Address Info</relationshipLabel>
    <relationshipName>Address_Info</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FEC_Address_Info__c/fields/FEC_Mailing_Address__c.field-meta.xml
<CustomField>
    <fullName>FEC_Mailing_Address__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Địa chỉ giao phát</description>
    <label>Mailing Address</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FEC_Customer_History__c/FEC_Customer_History__c.object-meta.xml
<CustomObject>
    <label>Customer History</label>
    <nameField>
        <label>Customer History Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Histories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FEC_Customer_History__c/fields/FEC_Address_Type__c.field-meta.xml
<CustomField>
    <fullName>FEC_Address_Type__c</fullName>
    <description>Loại địa chỉ</description>
    <label>Address Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FEC_Customer_History__c/fields/FEC_Block_Code_1__c.field-meta.xml
<CustomField>
    <fullName>FEC_Block_Code_1__c</fullName>
    <description>Tình trạng khóa thẻ 1</description>
    <label>Block Code 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FEC_Customer_History__c/fields/FEC_Block_Code__c.field-meta.xml
<CustomField>
    <fullName>FEC_Block_Code__c</fullName>
    <description>Tình trạng khóa thẻ</description>
    <label>Block Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FEC_Customer_History__c/fields/FEC_Mailing_Address__c.field-meta.xml
<CustomField>
    <fullName>FEC_Mailing_Address__c</fullName>
    <description>Địa chỉ giao phát</description>
    <label>Mailing Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FEC_Sub_Code__c/FEC_Sub_Code__c.object-meta.xml
<CustomObject>
    <label>FEC_Sub Code</label>
    <nameField>
        <label>FEC_Sub Code Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FEC_Sub Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FEC_Sub_Code__c/fields/FEC_Code__c.field-meta.xml
<CustomField>
    <fullName>FEC_Code__c</fullName>
    <description>Mã Code danh mục con</description>
    <label>Code</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/FEC_CardReplacementAddressController.cls
public with sharing class FEC_CardReplacementAddressController {
    @AuraEnabled
    public static List<FEC_Address_Info__c> getAddressInfos(String caseId) {
        try {
            Case objCase = [SELECT Id, FEC_Account_or_Contract__c FROM Case WHERE Id = :caseId];
            return [
                SELECT Id,
                    FEC_Address_Type__c,
                    FEC_Address__c,
                    FEC_Mailing_Address__c
                FROM FEC_Address_Info__c
                WHERE FEC_Customer_History__c = :objCase.FEC_Account_or_Contract__c
            ];
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static ReplaceCardResult checkProcessAction(String caseId) {
        try {
            ReplaceCardResult result = new ReplaceCardResult();
            List<String> inValidBlockCode = new List<String>{'F', 'S', 'G', 'N'};
            List<String> inValidBlockCode1 = new List<String>{'F', 'G', 'N'};
            Case objCase = [
                SELECT Id, 
                    FEC_Interaction__c,
                    FEC_Account_or_Contract__r.FEC_Block_Code__c,
                    FEC_Account_or_Contract__r.FEC_Block_Code_1__c
                FROM Case 
                WHERE Id = :caseId
            ];
            if ((String.isNotBlank(objCase.FEC_Account_or_Contract__r.FEC_Block_Code__c)
                    && inValidBlockCode.contains(objCase.FEC_Account_or_Contract__r.FEC_Block_Code__c))
                || (String.isNotBlank(objCase.FEC_Account_or_Contract__r.FEC_Block_Code_1__c)
                    && inValidBlockCode1.contains(objCase.FEC_Account_or_Contract__r.FEC_Block_Code_1__c))) {
                result.isShowAction = false;
                result.strMsg = 'Yêu cầu thay thế thẻ sẽ được chuyển đến CS D2C xử lý.';
            } else {
                List<Case> cases = [
                    SELECT Id 
                    FROM Case 
                    WHERE FEC_Interaction__c = :objCase.FEC_Interaction__c
                        AND (FEC_SubCode__r.FEC_Code__c = 'RC09.01'
                        OR FEC_SubCode__r.FEC_Code__c = 'RC09.02')
                ];
                if (!cases.isEmpty()) {
                    result.isShowAction = false;
                    result.strMsg = 'Yêu cầu thay thế thẻ sẽ được chuyển đến CS Support xử lý.';
                }
            }
            if (String.isBlank(result.strMsg)) {
                result.isShowAction = true;
            }
            return result;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    public class ReplaceCardResult {
        @AuraEnabled
        public Boolean isShowAction { get; set; }
        @AuraEnabled
        public String strMsg { get; set; }
    }
}