force-app/main/default/objects/CustomSync__c/CustomSync__c.object-meta.xml
<CustomObject>
    <description>Send Data to Bix</description>
    <label>Custom Sync</label>
    <nameField>
        <label>Custom Sync</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Custom Sync</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CustomSync__c/fields/EndAt__c.field-meta.xml
<CustomField>
    <fullName>EndAt__c</fullName>
    <label>End At</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/CustomSync__c/fields/StartAt__c.field-meta.xml
<CustomField>
    <fullName>StartAt__c</fullName>
    <label>Start At</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/CustomSync__c/fields/SyncFailed__c.field-meta.xml
<CustomField>
    <fullName>SyncFailed__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Số lượng sync Fail</description>
    <label>Sync Failed</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CustomSync__c/fields/SyncSuccessFully__c.field-meta.xml
<CustomField>
    <fullName>SyncSuccessFully__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Số lương sync thành công ở kỳ trước</description>
    <label>Sync SuccessFully</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CustomSync__c/fields/TargetObject__c.field-meta.xml
<CustomField>
    <fullName>TargetObject__c</fullName>
    <inlineHelpText>Object Api Name</inlineHelpText>
    <label>Target Object</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Case</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FEC_API_Log__c/FEC_API_Log__c.object-meta.xml
<CustomObject>
    <label>API Log</label>
    <nameField>
        <label>API Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>API Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FEC_API_Log__c/fields/FEC_Custom_Sync__c.field-meta.xml
<CustomField>
    <fullName>FEC_Custom_Sync__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Custom Sync</label>
    <referenceTo>CustomSync__c</referenceTo>
    <relationshipLabel>API Logs</relationshipLabel>
    <relationshipName>API_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FEC_API_Log__c/fields/FEC_Is_Success__c.field-meta.xml
<CustomField>
    <fullName>FEC_Is_Success__c</fullName>
    <label>Is Success</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FEC_Custom_Sync__c/FEC_Custom_Sync__c.object-meta.xml
<CustomObject>
    <description>Send Data to Bix</description>
    <label>FEC Custom Sync</label>
    <nameField>
        <label>FEC Custom Sync</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FEC Custom Sync</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/FEC_BatchCustomSync.cls
/*------------------------------------------------------------
Author:        Duan Nguyen
Company:       Isobar
Description:   Create Queue Sync Data To
Test Class:     
History
<Date>         <Authors Name>     <Brief Description of Change>
2026/03/31     Duan Nguyen          Init
------------------------------------------------------------*/ 
global class FEC_BatchCustomSync implements Database.Batchable<sObject>, Database.AllowsCallouts, Database.Stateful {
     
    private String query;
	private CustomSync__c cus;
	private Integer countSuccess = 0;
	private Integer countFail = 0;
    private List<FEC_API_Log__c> logs = new List<FEC_API_Log__c>();
    public FEC_BatchCustomSync(CustomSync__c recordCustom) { 
        this.cus = recordCustom;
    }
    
    global Database.QueryLocator start(Database.BatchableContext bc) {  
        DateTime toDate = DateTime.now();
        DateTime startTime = (cus != null && cus.EndAt__c != null) ? cus.EndAt__c : toDate.addHours(-1);
        return Database.getQueryLocator(getFieldSet(cus));
    } 
    global void execute(Database.BatchableContext bc, List<Case> scope) { 
        FEC_API_Log__c log = new FEC_API_Log__c();  
        try{
            if(scope == null || scope.isEmpty()){
                log.FEC_Error_Message__c = 'Record not found'; 
            }else{
                List<String> caseIds = new List<String>();
                for(Id caseId : new Map<Id, Case>(scope).keySet()) {
                    caseIds.add(String.valueOf(caseId));
                }
                log.FEC_Record_Data__c = JSON.serialize(scope);   
                log.FEC_Custom_Sync__c = cus.id;
                log = FEC_CustomSyncCallout.sendRequest(cus,log,scope);  
                if (log.FEC_Is_Success__c ?? false) { 
                    countSuccess++;
                } else{ 
                    countFail++;
                } 
            }
        }Catch(Exception e){ 
            log.FEC_Error_Message__c = 'Exception FEC_BatchCustomSync: Line ' + e.getLineNumber() + ' - '+e.getMessage();
        }
        logs.add(log);
    }
 
    global void finish(Database.BatchableContext bc) { 
        cus.StartAt__c = cus.EndAt__c ?? System.now().addHours(-1);
        cus.EndAt__c = System.now();
        cus.SyncSuccessFully__c = countSuccess;
        cus.SyncFailed__c = countFail;
        update cus;
        if(!logs.isEmpty()){
            upsert logs;
        }
    }

    private String getFieldSet(CustomSync__c cus) {  
        Schema.SObjectType targetType = Schema.getGlobalDescribe().get(cus.TargetObject__c); 
        Map<String, Schema.FieldSet> fieldSetMap = targetType.getDescribe().fieldSets.getMap();
        Set<String> queryFields = new Set<String>{}; 
        Integer index = 1;
        while (fieldSetMap.containsKey(cus.FieldSetsTarget__c + index)) {
            for (Schema.FieldSetMember f : fieldSetMap.get(cus.FieldSetsTarget__c + index).getFields()) {
                queryFields.add(f.getFieldPath());
            }
            index++;
        }
        if(queryFields.isEmpty())  return 'Select Id from '+ cus.TargetObject__c + ' limit 0'; 
        String fieldsPart = String.join(new List<String>(queryFields), ', ');

        // String wherePart = ' WHERE (LastModifiedDate > :startTime AND LastModifiedDate <= :toDate) ' +
        //                 ' OR (CreatedDate > :startTime AND CreatedDate <= :toDate) limit 300'; // test
        
        String wherePart = ' limit 300'; // test
        
        return 'SELECT ' + fieldsPart + ' FROM ' + cus.TargetObject__c + wherePart;
    }
}