force-app/main/default/objects/FEC_Custom_Sync__c/FEC_Custom_Sync__c.object-meta.xml
<CustomObject>
    <description>Send Data to Bix</description>
    <label>FEC Custom Sync</label>
    <nameField>
        <label>FEC Custom Sync</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FEC Custom Sync</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FEC_Custom_Sync__c/fields/FEC_Active__c.field-meta.xml
<CustomField>
    <fullName>FEC_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FEC_Custom_Sync__c/fields/FEC_Case_Business_Code__c.field-meta.xml
<CustomField>
    <fullName>FEC_Case_Business_Code__c</fullName>
    <inlineHelpText>This field only applies when the Target Object is Case.</inlineHelpText>
    <label>Case Business Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FEC_Custom_Sync__c/fields/FEC_End_At__c.field-meta.xml
<CustomField>
    <fullName>FEC_End_At__c</fullName>
    <label>End At</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/FEC_Custom_Sync__c/fields/FEC_Mapping_Data_Type__c.field-meta.xml
<CustomField>
    <fullName>FEC_Mapping_Data_Type__c</fullName>
    <label>Mapping Data Type</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/FEC_Custom_Sync__c/fields/FEC_Processing_Quantity__c.field-meta.xml
<CustomField>
    <fullName>FEC_Processing_Quantity__c</fullName>
    <defaultValue>10</defaultValue>
    <description>Processing quantity run on batch</description>
    <label>Processing Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FEC_Custom_Sync__c/fields/FEC_Request_Body_Mapping__c.field-meta.xml
<CustomField>
    <fullName>FEC_Request_Body_Mapping__c</fullName>
    <label>Request Body Mapping</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/FEC_Custom_Sync__c/fields/FEC_Start_At__c.field-meta.xml
<CustomField>
    <fullName>FEC_Start_At__c</fullName>
    <label>Start At</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/FEC_Custom_Sync__c/fields/FEC_Sync_Failed__c.field-meta.xml
<CustomField>
    <fullName>FEC_Sync_Failed__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Số lượng sync Fail</description>
    <label>Sync Failed</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FEC_Custom_Sync__c/fields/FEC_Sync_Successfully__c.field-meta.xml
<CustomField>
    <fullName>FEC_Sync_Successfully__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Số lương sync thành công ở kỳ trước</description>
    <label>Sync SuccessFully</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FEC_Custom_Sync__c/fields/FEC_Sync_To__c.field-meta.xml
<CustomField>
    <fullName>FEC_Sync_To__c</fullName>
    <label>Sync To</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bix</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FEC_Custom_Sync__c/fields/FEC_Table_Name__c.field-meta.xml
<CustomField>
    <fullName>FEC_Table_Name__c</fullName>
    <label>Table Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FEC_Custom_Sync__c/fields/FEC_Target_Object__c.field-meta.xml
<CustomField>
    <fullName>FEC_Target_Object__c</fullName>
    <label>TargetObject</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FEC_Custom_Sync__c/fields/FEC_Total_Record_Sync__c.field-meta.xml
<CustomField>
    <fullName>FEC_Total_Record_Sync__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total Record Sync</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/FEC_ScheduledSyncDataToBix.cls
/*------------------------------------------------------------
Author:        Duan Nguyen
Company:       Isobar
Description:   Create Schedule Sync Data To Bix
Test Class:     FEC_CustomSyncAllInOneTest
History
<Date>         <Authors Name>     <Brief Description of Change>
2026/03/31     Duan Nguyen          Init
------------------------------------------------------------*/
/*
    FEC_ScheduledSyncDataToBix syncJob = new FEC_ScheduledSyncDataToBix(); 
    String cronExp = '0 0 * * * ?'; 
    String jobID = System.schedule('Custom Sync Hourly', cronExp, syncJob);
*/
global class FEC_ScheduledSyncDataToBix implements  Schedulable {
    global void execute(SchedulableContext sc) { 
        Try{
             run();
        }Catch(Exception e){
            System.debug('Schedule Sync Data To bix Error: Line '+e.getLineNumber() + ' - ' + e.getMessage());
        }
    }
    public static void run(){
        List<FEC_Custom_Sync__c> lst = [Select id, Name,
                                        FEC_Sync_Failed__c,
                                        FEC_Sync_Successfully__c,
                                        FEC_Sync_To__c,
                                        FEC_Active__c, 
                                        FEC_Start_At__c,
                                        FEC_End_At__c,
                                        FEC_Processing_Quantity__c,
                                        FEC_Case_Business_Code__c, 
                                        FEC_Table_Name__c,
                                        FEC_Total_Record_Sync__c,
                                        FEC_Target_Object__c,
                                        FEC_Request_Body_Mapping__c,
                                        FEC_Mapping_Data_Type__c
                                        from FEC_Custom_Sync__c
                                        where FEC_Sync_To__c = 'Bix' and FEC_Active__c = true]; 
            if(!lst.isEmpty()){  
                Map<Id, FEC_Custom_Sync__c> mapCustomSync = new Map<Id, FEC_Custom_Sync__c>(lst); // ReSync
                // Sync New
                FEC_QueueRunBatchSync nextJob = new FEC_QueueRunBatchSync(lst);  
                System.enqueueJob(nextJob);   
                // ReSync
                FEC_BatchReCallCustomSync batch = new FEC_BatchReCallCustomSync(mapCustomSync);
                Database.executeBatch(batch,1);
            }  
    }
     
}