force-app/main/default/objects/FEC_Business_Process__c/FEC_Business_Process__c.object-meta.xml
<CustomObject>
    <label>FEC_Business Process</label>
    <nameField>
        <label>Business Process  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FEC_Business Process</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FEC_Business_Process__c/fields/FEC_Active__c.field-meta.xml
<CustomField>
    <fullName>FEC_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Trạng thái quy trình</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FEC_Business_Process__c/fields/FEC_Code__c.field-meta.xml
<CustomField>
    <fullName>FEC_Code__c</fullName>
    <description>Mã Code sản phẩm</description>
    <externalId>true</externalId>
    <label>Code</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/FEC_Category__c/FEC_Category__c.object-meta.xml
<CustomObject>
    <label>FEC Category</label>
    <nameField>
        <label>Category  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FEC Category</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FEC_Category__c/fields/FEC_Active__c.field-meta.xml
<CustomField>
    <fullName>FEC_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Trạng thái danh mục</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FEC_Category__c/fields/FEC_Code__c.field-meta.xml
<CustomField>
    <fullName>FEC_Code__c</fullName>
    <description>Mã Code danh mục</description>
    <label>Code</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/FEC_Category__c/fields/FEC_Product_Type__c.field-meta.xml
<CustomField>
    <fullName>FEC_Product_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Tên loại sản phẩm Product Type</description>
    <label>Product Type</label>
    <referenceTo>FEC_Product_Type__c</referenceTo>
    <relationshipLabel>Categories</relationshipLabel>
    <relationshipName>Categories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FEC_Master_Data_Setting__c/FEC_Master_Data_Setting__c.object-meta.xml
<CustomObject>
    <description>Là bảng dữ liệu chứa bộ Setting của một bộ Nature of Case</description>
    <label>Master Data Setting</label>
    <nameField>
        <displayFormat>MDS-{0}</displayFormat>
        <label>MDS Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Master Data Setting</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/FEC_Master_Data_Setting__c/fields/FEC_Code__c.field-meta.xml
<CustomField>
    <fullName>FEC_Code__c</fullName>
    <externalId>true</externalId>
    <label>FEC Code </label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/FEC_Master_Data_Setting__c/fields/FEC_Field_Status__c.field-meta.xml
<CustomField>
    <fullName>FEC_Field_Status__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Trạng thái hiển thị của trường trên màn hình Case</description>
    <label>Field Status</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FEC_Master_Data_Setting__c/fields/FEC_Nature_Of_Case__c.field-meta.xml
<CustomField>
    <fullName>FEC_Nature_Of_Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Tên bộ Nature of Case</description>
    <label>Nature Of Case</label>
    <referenceTo>FEC_Nature_of_Case__c</referenceTo>
    <relationshipLabel>Master Data Setting</relationshipLabel>
    <relationshipName>Master_Data_Setting</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FEC_Master_Data_Setting__c/fields/FEC_Section__c.field-meta.xml
<CustomField>
    <fullName>FEC_Section__c</fullName>
    <description>Tên Section hiển thị</description>
    <label>Section</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FEC_Nature_of_Case__c/FEC_Nature_of_Case__c.object-meta.xml
<CustomObject>
    <description>Là bảng dữ liệu chứa bộ Nature of Case</description>
    <label>Nature of Cases</label>
    <nameField>
        <displayFormat>NOC-{0}</displayFormat>
        <label>Nature of Case Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Nature of Cases</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/FEC_Nature_of_Case__c/fields/FEC_Active__c.field-meta.xml
<CustomField>
    <fullName>FEC_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Trạng thái của bộ NOC</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FEC_Nature_of_Case__c/fields/FEC_Business_Process__c.field-meta.xml
<CustomField>
    <fullName>FEC_Business_Process__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Thông tin luồng quy trình</description>
    <label>Business Process</label>
    <referenceTo>FEC_Business_Process__c</referenceTo>
    <relationshipName>Nature_of_Case</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FEC_Nature_of_Case__c/fields/FEC_Category__c.field-meta.xml
<CustomField>
    <fullName>FEC_Category__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Thông tin danh mục</description>
    <label>Category</label>
    <referenceTo>FEC_Category__c</referenceTo>
    <relationshipName>Nature_of_Case</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FEC_Nature_of_Case__c/fields/FEC_Customer_Type__c.field-meta.xml
<CustomField>
    <fullName>FEC_Customer_Type__c</fullName>
    <label>Customer Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Customer_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FEC_Nature_of_Case__c/fields/FEC_Product_Type__c.field-meta.xml
<CustomField>
    <fullName>FEC_Product_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Thông tin loại sản phẩm</description>
    <label>Product Type</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>FEC_Product_Type__c.FEC_Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>FEC_Product_Type__c</referenceTo>
    <relationshipLabel>Nature of Cases</relationshipLabel>
    <relationshipName>Nature_of_Case</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FEC_Nature_of_Case__c/fields/FEC_Sub_Category__c.field-meta.xml
<CustomField>
    <fullName>FEC_Sub_Category__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Thông tin danh mục phụ</description>
    <label>Sub Category</label>
    <referenceTo>FEC_Sub_Category__c</referenceTo>
    <relationshipLabel>Nature of Cases</relationshipLabel>
    <relationshipName>Nature_of_Case</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FEC_Nature_of_Case__c/fields/FEC_Sub_Code__c.field-meta.xml
<CustomField>
    <fullName>FEC_Sub_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Thông tin danh mục con</description>
    <label>Sub Code</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>FEC_Sub_Code__c.FEC_Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>FEC_Sub_Code__c</referenceTo>
    <relationshipLabel>Nature of Cases</relationshipLabel>
    <relationshipName>Nature_of_Case</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FEC_Product_Type__c/FEC_Product_Type__c.object-meta.xml
<CustomObject>
    <description>Là loại sản phẩm trong bộ Nature of Case</description>
    <label>Product Type</label>
    <nameField>
        <label>Product Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Type</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

fecdat/force-app/main/default/objects/FEC_Product_Type__c/fields/FEC_Active__c.field-meta.xml
<CustomField>
    <fullName>FEC_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Trạng thái loại sản phẩm</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FEC_Product_Type__c/fields/FEC_Code__c.field-meta.xml
<CustomField>
    <fullName>FEC_Code__c</fullName>
    <description>Mã Code sản phẩm</description>
    <label>Code</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/FEC_Sub_Category__c/FEC_Sub_Category__c.object-meta.xml
<CustomObject>
    <label>FEC Sub Category</label>
    <nameField>
        <label>Sub Category  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FEC Sub Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FEC_Sub_Category__c/fields/FEC_Active__c.field-meta.xml
<CustomField>
    <fullName>FEC_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Trang thái SubCategory</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FEC_Sub_Category__c/fields/FEC_Code__c.field-meta.xml
<CustomField>
    <fullName>FEC_Code__c</fullName>
    <description>Mã Code danh mục phụ</description>
    <externalId>true</externalId>
    <label>Code</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/FEC_Sub_Code__c/FEC_Sub_Code__c.object-meta.xml
<CustomObject>
    <label>FEC_Sub Code</label>
    <nameField>
        <label>FEC_Sub Code Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FEC_Sub Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FEC_Sub_Code__c/fields/FEC_Code__c.field-meta.xml
<CustomField>
    <fullName>FEC_Code__c</fullName>
    <description>Mã Code danh mục con</description>
    <label>Code</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/globalValueSets/Customer_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Existing</fullName>
        <default>true</default>
        <label>Existing</label>
    </customValue>
    <customValue>
        <fullName>Non-existing</fullName>
    </customValue>
    <customValue>
        <fullName>All</fullName>
    </customValue>
    <masterLabel>Customer Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/FEC_LiveMDReviewDeepTest.cls
/**
 * @description Deep tests for FEC_LiveMasterDataReviewController.
 * @author      DAT NGO
 * @date        2026-06-03
 * @module      Live Layer
 */
@IsTest
private class FEC_LiveMDReviewDeepTest {

    @testSetup
    static void setup() {
        FEC_Product_Type__c pt = new FEC_Product_Type__c(
            Name = 'PT_LMR', FEC_Code__c = 'PT_LMR_1', FEC_Active__c = true
        );
        insert pt;
        FEC_Business_Process__c bp = new FEC_Business_Process__c(
            Name = 'BP_LMR', FEC_Code__c = 'BP_LMR_1'
        );
        insert bp;
        FEC_Category__c cat = new FEC_Category__c(
            Name = 'CAT_LMR', FEC_Code__c = 'CAT_LMR_1', FEC_Active__c = true
        );
        insert cat;
        FEC_Sub_Category__c subCat = new FEC_Sub_Category__c(
            Name = 'SCAT_LMR', FEC_Code__c = 'SCAT_LMR_1', FEC_Active__c = true
        );
        insert subCat;
        FEC_Sub_Code__c subCode = new FEC_Sub_Code__c(
            Name = 'SC_LMR', FEC_Code__c = 'SC_LMR_1', FEC_Active__c = true
        );
        insert subCode;

        FEC_Nature_of_Case__c noc = new FEC_Nature_of_Case__c(
            FEC_Product_Type__c = pt.Id,
            FEC_Business_Process__c = bp.Id,
            FEC_Category__c = cat.Id,
            FEC_Sub_Category__c = subCat.Id,
            FEC_Sub_Code__c = subCode.Id,
            FEC_Customer_Type__c = 'Existing',
            FEC_Code__c = 'NOC_LMR_1'
        );
        insert noc;

        // Live MDS setting
        insert new FEC_Master_Data_Setting__c(
            FEC_Code__c = 'MDS_LMR_1',
            FEC_Nature_Of_Case__c = noc.Id,
            FEC_Field_Status__c = true,
            FEC_Section__c = 'Section A'
        );
    }

    @IsTest
    static void testGetCustomerTypeOptions_HasData() {
        Test.startTest();
        List<Map<String, String>> opts = FEC_LiveMasterDataReviewController.getCustomerTypeOptions();
        Test.stopTest();
        Assert.isFalse(opts.isEmpty(), 'Customer types phải có');
    }

    @IsTest
    static void testGetProductOptions_ValidCustomerType() {
        Test.startTest();
        List<Map<String, String>> opts = FEC_LiveMasterDataReviewController.getProductOptions('Existing');
        Test.stopTest();
        Assert.isFalse(opts.isEmpty(), 'Products phải có');
    }

    @IsTest
    static void testGetBizOptions_ValidProduct() {
        Id ptId = [SELECT Id FROM FEC_Product_Type__c LIMIT 1].Id;
        Test.startTest();
        List<Map<String, String>> opts = FEC_LiveMasterDataReviewController.getBizOptions(String.valueOf(ptId));
        Test.stopTest();
        Assert.isFalse(opts.isEmpty());
    }

    @IsTest
    static void testGetCategoryOptions_ValidIds() {
        Id ptId = [SELECT Id FROM FEC_Product_Type__c LIMIT 1].Id;
        Id bpId = [SELECT Id FROM FEC_Business_Process__c LIMIT 1].Id;
        Test.startTest();
        List<Map<String, String>> opts = FEC_LiveMasterDataReviewController.getCategoryOptions(
            String.valueOf(ptId), String.valueOf(bpId)
        );
        Test.stopTest();
        Assert.isFalse(opts.isEmpty());
    }

    @IsTest
    static void testGetSubCatOptions_ValidIds() {
        Id ptId = [SELECT Id FROM FEC_Product_Type__c LIMIT 1].Id;
        Id bpId = [SELECT Id FROM FEC_Business_Process__c LIMIT 1].Id;
        Id catId = [SELECT Id FROM FEC_Category__c LIMIT 1].Id;
        Test.startTest();
        List<Map<String, String>> opts = FEC_LiveMasterDataReviewController.getSubCatOptions(
            String.valueOf(ptId), String.valueOf(bpId), String.valueOf(catId)
        );
        Test.stopTest();
        Assert.isFalse(opts.isEmpty());
    }

    @IsTest
    static void testGetSubCodeOptions_ValidIds() {
        Id ptId = [SELECT Id FROM FEC_Product_Type__c LIMIT 1].Id;
        Id bpId = [SELECT Id FROM FEC_Business_Process__c LIMIT 1].Id;
        Id catId = [SELECT Id FROM FEC_Category__c LIMIT 1].Id;
        Id subCatId = [SELECT Id FROM FEC_Sub_Category__c LIMIT 1].Id;
        Test.startTest();
        List<Map<String, String>> opts = FEC_LiveMasterDataReviewController.getSubCodeOptions(
            String.valueOf(ptId), String.valueOf(bpId), String.valueOf(catId), String.valueOf(subCatId)
        );
        Test.stopTest();
        Assert.isNotNull(opts);
    }

    @IsTest
    static void testGetComparisonData_LiveOnly_ToNew() {
        Id ptId = [SELECT Id FROM FEC_Product_Type__c LIMIT 1].Id;
        Id bpId = [SELECT Id FROM FEC_Business_Process__c LIMIT 1].Id;
        Id catId = [SELECT Id FROM FEC_Category__c LIMIT 1].Id;
        Id subCatId = [SELECT Id FROM FEC_Sub_Category__c LIMIT 1].Id;
        Id subCodeId = [SELECT Id FROM FEC_Sub_Code__c LIMIT 1].Id;

        Test.startTest();
        FEC_MasterDataReviewController.ComparisonResult result = FEC_LiveMasterDataReviewController.getComparisonData(
            String.valueOf(ptId), String.valueOf(bpId), String.valueOf(catId),
            String.valueOf(subCatId), String.valueOf(subCodeId)
        );
        Test.stopTest();
        Assert.isNotNull(result);
        // Live exists but no MDM → newList should have entry
        Assert.isFalse(result.newList.isEmpty(), 'Live MDS without MDM → newList');
    }

    @IsTest
    static void testGetComparisonData_NoMatch() {
        Test.startTest();
        FEC_MasterDataReviewController.ComparisonResult result = FEC_LiveMasterDataReviewController.getComparisonData(
            'a0X000000000000', 'a0X000000000001', 'a0X000000000002', 'a0X000000000003', 'a0X000000000004'
        );
        Test.stopTest();
        Assert.isNotNull(result);
        Assert.isTrue(result.newList.isEmpty());
        Assert.isTrue(result.updateList.isEmpty());
    }
}